### ISSUE TITLE
Test file.general is not consistent with types in schema

### ISSUE THREAD

**Issue by Mikulas** [nextras/orm#100]
`author.born` is defined as `date` in both engines. The test case is valid and it should probably behave like this, but it's inconsistent. Is there a reason for the field not to be defined as datetime and timestamp in mysql and pg respectively?

https://github.com/nextras/orm/blob/master/tests/cases/integration/Mapper/file.general.phpt#L73

**Comment by hrach** [comment]
Sorry, I don't get it fully. :crying_cat_face:

**Comment by Mikulas** [comment]
It's a very minor thing, it's just weird that a column that will truncate to date is tested for time precision. This test would fail if the entity was persisted and loaded (obviously not from identity map) as it would have passed
```
Assert::same('2000-01-01 00:00:00', $author->born->format('Y-m-d H:i:s'));
```
instead.

**Comment by hrach** [comment]
Ou yes! Such nice issue number wasted for such minor thing :D :smile_cat:

**Comment by Mikulas** [comment]
Yeah right sorry about that :D

**Comment by hrach** [comment]
> This test would fail if the entity was persisted and loaded (obviously not from identity map)

actually, it does not use an identity map, there is created new model instance between persistance & assert.
