### ISSUE TITLE
AnnotationParser: one primary modifier

### ISSUE THREAD

**Issue by hrach** [nextras/orm#108]
There is, probably, a bug when entity has primary modifier redefined with it's primary key. This will include a bigger refactoring, probably with a BC break, each entity will have to define it's primary property and Nextras\Orm\Entity\Enity will not have a predefined primary key. Will solve #75.

**Comment by f3l1x** [comment]
It's also for case when table has a composite key for example.

category (id)
category_has_tag (category_id, tag_id, extra_column)
tag (id)

Right?

**Comment by hrach** [comment]
@f3l1x no.

**Comment by f3l1x** [comment]
Could you please help me with this relationships? It is m:n, but how to define it?

**Comment by hrach** [comment]
Just define the middle entity. And composite PK. See TagFollower in tests.

**Comment by f3l1x** [comment]
@hrach Thank you.
