### ISSUE TITLE
Ordering over 1:1d relation

### ISSUE THREAD

**Issue by f3l1x** [nextras/orm#120]
Relations:

A <1:1d> B. 

```php
$aRepository->findAll()->orderBy('this->b->changed', 'DESC');
```

In the code: https://github.com/nextras/orm/blob/5ce2c40686ec32a14c13303a12d61b2f3a263c90/src/Mapper/Dbal/QueryBuilderHelper.php#L89

When it's removed, it works nice. 

How can I order solve it? Thx.

**Comment by hrach** [comment]
Seem this could be easily fixed.

**Comment by f3l1x** [comment]
@hrach Is there any workaround? I need it really soon. Thx.

**Comment by f3l1x** [comment]
@hrach Thank you.

**Comment by hrach** [comment]
Uh, I thank you for the bug report!
