### ISSUE TITLE
Support more conditions in Repository 

### ISSUE THREAD

**Issue by f3l1x** [nextras/orm#127]
In almost every searching I use LIKE. At this moment I have to do that in mapper. =/

**Comment by hrach** [comment]
Thins need a deeper implementatio of filtering feature to allow such filtering also in ArrayCollection.

**Comment by hrach** [comment]
Custom functions merged: https://github.com/nextras/orm/commit/8bea3f4cf5da754260a9f5806259d50153af1207

Like custom function:
- impl: https://github.com/nextras/orm/blob/8bea3f4cf5da754260a9f5806259d50153af1207/tests/inc/model/LikeFilterFunction.php
- registration: https://github.com/nextras/orm/blob/8bea3f4cf5da754260a9f5806259d50153af1207/tests/inc/model/book/BooksRepository.php#L40-L41
- usage: https://github.com/nextras/orm/blob/8bea3f4cf5da754260a9f5806259d50153af1207/tests/cases/integration/Collection/collection.customFunctions.phpt#L31-L32

Docs will be updated later.

**Comment by camohub** [comment]
This LIKE syntax looks little weird. It does not seem like `books->findBy(['title~=' =>'Some title'])` Is not possible to write it better?
