### ISSUE TITLE
Dependency on Kdyby/Events with enabled panel (debugger: on) leaks memory

### ISSUE THREAD

**Issue by Mikulas** [nextras/orm#140]
Orm event `onBeforePersist` calls into kdyby/events, which stores the event and it's arguments. This adds reference to the entity tree and `clearIdentityMapAndCaches` does not clear it from memory.

This is an ugly leak which I only pin-pointed after numerous hours. It might be classified as an upstream bug (panel code should probably not be invoked in CLI mode, which is presumably the only valid mode for long-running memory-aware php processes). Different solution would be purging entities from `EventArgs` in `onFree`. Yet another solution would be adding this as a warning to documentation, or even creating a new chapter on how to use orm in long-running processes.

I'm not sure what the next step is here, mostly this should serve as a help for those searching for similar issue in the future.

This is not resolved by #139

**Comment by hrach** [comment]
I wonder what is your solution? Disabling panel or somehow cleaning references in onFree?

**Comment by JanTvrdik** [comment]
I consider this an upstream bug.

**Comment by Mikulas** [comment]
I guess `onFree` would be too magical. Closing in favor of https://github.com/Kdyby/Events/issues/86

**Comment by hrach** [comment]
Let's track here adding some doc, ok?

**Comment by hrach** [comment]
Fixed in Kdyby/eventes, I do not see any strong reason to document this :-)
