### ISSUE TITLE
ArrayCollectionHelper - invalid comparing

### ISSUE THREAD

**Issue by f3l1x** [nextras/orm#145]
```php
const OPERATOR_EQUAL_OR_GREATER = '=>';
const OPERATOR_EQUAL_OR_SMALLER = '=<';
```
But parseCondition support only => OR =<

```php
preg_match('#^([\w\\\]+(?:->\w+)*)(!|!=|<=|>=|=|>|<)?$#', $condition, $matches)
```

When I use => / =< it ends with (https://github.com/nextras/orm/blob/v1.1.4/src/Collection/Helpers/ConditionParserHelper.php#L28)

```php
// ConditionParserHelper
throw new InvalidArgumentException('Unsupported condition format.');
```

When I use >= / <= it ends with (https://github.com/nextras/orm/blob/v1.1.4/src/Collection/Helpers/ArrayCollectionHelper.php#L94)

```php
// ArrayCollectionHelper
throw new InvalidArgumentException();
```

**Comment by hrach** [comment]
oh, that's stupid :(

**Comment by f3l1x** [comment]
Thanks. :+1:
