### ISSUE TITLE
How to inspect SQL queries?

### ISSUE THREAD

**Issue by MartyIX** [nextras/orm#146]
Hi,

Nette\Database allows to track SQL queries in the debugger bar. Can I enable SQL query logging in Nextras\ORM? It would help me debug my application and verify that everything works as it is supposed.

Thanks,
Martin

**Comment by hrach** [comment]
Well, orm uses nextras dbal which has the Nette DI extension that enables it's own panel for tracy. Of course, you can add your own hook on dbal's connection to log it somewhere as you wish.

**Comment by MartyIX** [comment]
Thanks.

note to self: `\Nextras\Dbal\Connection::$onQuery`
