### ISSUE TITLE
CachedPlatform - error at 2.0.0-beta3

### ISSUE THREAD

**Issue by f3l1x** [nextras/orm#154]
Beta2: works
Beta3: not works

Throwed: 

*Argument 2 passed to Nextras\Dbal\Platforms\CachedPlatform::__construct() must implement interface Nette\Caching\IStorage, instance of Nette\Caching\Cache given, called in ...vendor/nextras/orm/src/Mapper/Dbal/StorageReflection/StorageReflection.php on line 52 in .../vendor/nextras/dbal/src/Platforms/CachedPlatform.php:25*

**Comment by hrach** [comment]
Update also nextras Dbal.

**Comment by f3l1x** [comment]
I have only "nextras\orm: ~2.0.0" with "minimum-stability": "dev".

**Comment by hrach** [comment]
So try to run proper update of all. Dependencies are defined correctly.

**Comment by f3l1x** [comment]
Are you sure? 

https://github.com/nextras/dbal/blob/v2.0.0-beta2/src/Platforms/CachedPlatform.php

```php
class CachedPlatform implements IPlatform
{
	/** @var IPlatform */
	private $platform;
	/** @var Cache */
	private $cache;
	public function __construct(Connection $connection, IStorage $storage)
	{
		$key = md5(json_encode($connection->getConfig()));
		$this->platform = $connection->getPlatform();
		$this->cache = new Cache($storage, "nextras.dbal.platform.$key");
	}
```

**Comment by hrach** [comment]
Yes. This is the tag, the dev is master, where it's ok. https://github.com/nextras/dbal/blob/17c1e7f851ef89a571b8c187da2e290d7cf1edfa/composer.json#L30-L32

**Comment by hrach** [comment]
I suggest you adding nextras/dbal as dependency, you definitely use it directly, so it should be your dependency.
