### ISSUE TITLE
Typo in AnnotationParser

### ISSUE THREAD

**Issue by Hologos** [nextras/orm#155]
There is a typo in AnnotationParser on lines 262 and 270 in v1.1.
```php
throw new InvalidStateException("Relationship in {$this->currentReflection->name}::\${$propertyMetadata->name} points to UKNONW entity.");
```

I found it while debbuging. I was getting this Exception because I used only a single colon instead of double colon in relationship definition. Adding additional check would be great.

**Comment by hrach** [comment]
Thank you for the bugreport. I will try to add an additional check.

**Comment by pryznar** [comment]
@Hologos AnnotaionParser was replaced by MetadataParser
@hrach more similar typos :)
https://github.com/nextras/orm/search?utf8=%E2%9C%93&q=uknown

**Comment by hrach** [comment]
Obviously too many "n" for me :-´)
