### ISSUE TITLE
Back reference of 1:1 relationships fetches parent entities again.

### ISSUE THREAD

**Issue by hrach** [nextras/orm#157]
Flow:
- https://github.com/componette/componette.com/blob/6edb23efbe4bdb62644d90f144cb4c367db541a3/app/modules/front/controls/AddonList/templates/list.latte#L2-L30
- https://github.com/componette/componette.com/blob/6edb23efbe4bdb62644d90f144cb4c367db541a3/app/modules/front/controls/AddonMeta/templates/short.latte#L1-L33
- https://github.com/componette/componette.com/blob/6edb23efbe4bdb62644d90f144cb4c367db541a3/app/model/orm/github/Github.php#L54

![fq6n7cm](https://cloud.githubusercontent.com/assets/284263/13033790/92ba7e4c-d323-11e5-9621-4a345cb71bd2.png)

thanks @f3l1x for bugreport.

**Comment by f3l1x** [comment]
@hrach Thanks.

Let me know after, I'll test it on my code. 

Btw, these queries are also without Github/Linker (https://github.com/componette/componette.com/blob/6edb23efbe4bdb62644d90f144cb4c367db541a3/app/model/orm/github/Github.php#L54). Just list addons and show github description.

```smarty
<div n:foreach="$addons as $addon">
    <p>{$addon->github->description|truncate:150}</p>
</div>
```

**Comment by f3l1x** [comment]
@hrach One more thing. I thing there could be bug at 1:1 relation, because this code.

```smart
<div n:foreach="$addons as $addon">
    <p>{$addon->github->id}</p>
    <p>{$addon->composer->id}</p>
</div>
```

Genererates:

![screenshot_021416_021131_pm](https://cloud.githubusercontent.com/assets/538058/13033836/d8fde7ee-d324-11e5-804d-d45a8b9969ca.jpg)
