### ISSUE TITLE
Default entity value defined by callback

### ISSUE THREAD

**Issue by Zarganwar** [nextras/orm#167]
Is it bad idea or not? I don't know if entity default value represents only DB default value (in orm philosophy) or can be something more. 
e.g.: `{default ["class", "method"]}`

**Comment by hrach** [comment]
You may set such default value in onCreate() event, which is called only when the entity is created.

```php
class MyEntity extends Entity
{
     protected function onCreate()
     {
          parent::onCreate();
          $this->name = Class::method();
     }
}
```

**Comment by hrach** [comment]
I'm closing this. It may be re

**Comment by hrach** [comment]
Closing for now, feel free to ask for reopen.
