### ISSUE TITLE
Update only modified columns

### ISSUE THREAD

**Issue by JanTvrdik** [nextras/orm#170]
Current behavior greatly increases probability of race conditions.

**Comment by hrach** [comment]
Commited, but not wel tested, since the majority of tests doesn flush Identity map. Testers welcomed!

**Comment by jkavalik** [comment]
When you set a property to its original value, the column gets updated even when it is not really needed. When editing an entity using forms, the form data overwrite all properties too even when there was no real change. The result is that all columns are updated (including cascading full update to associated entities in some cases). Not sure which layer should detect the "no-real-change-happened" condition, if the form or the orm.

**Comment by JanTvrdik** [comment]
That seems like expected behavior to me. Doing it otherwise may lead to inconsistent database state.

**Comment by jkavalik** [comment]
@JanTvrdik Not sure I follow. Partial update is possible even now with this feature, so I can't see how finer detection of what changed would lead to a bigger chance of inconsistent state.

**Comment by hrach** [comment]
Are you solving a real problem? What is it?

**Comment by jkavalik** [comment]
@hrach We log update history of each entity - currently entire entity state is saved in a listener. We would like to only store the modified fields in a log table (so you can easily fetch the history for any given field). But as the feature works now, when the entity is updated from a form, all fields are set and all fields would be stored even if there were no actual change. For it to work there would have to be some check that oldValue != newValue for a property to be marked as modified (currently just invoking the setter with any value is enough). We could probably implement such checks on the form->entity-update boundary, but the ORM seems a better place for that imho.
