### ISSUE TITLE
Duplicate key value violates unique constraint in relationships

### ISSUE THREAD

**Issue by hrach** [nextras/orm#171]
https://github.com/nextras/orm/commit/f55963a49169d1ce3d59c5ce92ac8ce9566c26b0 probably breaks something and may result into `duplicate key value violates unique constraint`

**Comment by JanTvrdik** [comment]
the commit was reverted https://github.com/nextras/orm/commit/a2fd613be60928e90f42f40e16d8dc857124fcd2 but the issue requires more investigation to fully understand it

**Comment by hrach** [comment]
I guess you would like to fix the caching mechanism here: https://github.com/nextras/orm/blob/a2fd613be60928e90f42f40e16d8dc857124fcd2/src/Mapper/Dbal/RelationshipMapperManyHasMany.php#L93-L99, do you?

**Comment by JanTvrdik** [comment]
@hrach Unfortunately I don't understand that part of the code at all.
