### ISSUE TITLE
AddMapping should warn on overwrite

### ISSUE THREAD

**Issue by Mikulas** [nextras/orm#174]
I propose adding a warning/exception when `addMapping` would overwrites already mapped column

---

For example: I unintentionally overwrote mapping for `zamestnanecID` and got error when `id` was `NULL` (because it was no longer mapped)

```php
protected function createStorageReflection()
{
	$ref = parent::createStorageReflection();
	$ref->addMapping('id', 'zamestnanecID');
	$ref->addMapping('uzivatelskyUcet', 'zamestnanecID');
	return $ref;
}    
```

**Comment by JanTvrdik** [comment]
This would make it impossible to change existing mapping.

**Comment by Mikulas** [comment]
Current behaviour is incorrect though. If more than one entity property is mapped to single column, it silently ignores the first mapping.
