### ISSUE TITLE
Problem with DATE_FORMAT()

### ISSUE THREAD

**Issue by daihousl** [nextras/orm#176]
This function use % as formater http://www.w3schools.com/sql/func_date_format.asp
And this is problem. It cause "Nextras\Dbal\InvalidArgumentException - Unknown modifier %Y"

**Comment by hrach** [comment]
How do you pass the arugment to the dateformat?

**Comment by daihousl** [comment]
@hrach I try this ``DATE_FORMAT(users.created_at, "%Y-%c")`` && ``DATE_FORMAT(users.created_at, '%Y-%c')``

**Comment by JanTvrdik** [comment]
~~~php
query('%raw', '...DATE_FORMAT(users.create_date, "%Y-%c")...')
~~~

or 

~~~php
query('...DATE_FORMAT(users.create_date, %s)...', '%Y-%c')
~~~

**Comment by Mikulas** [comment]
or
```php
query('...DATE_FORMAT(users.create_date, %s)...', '%%Y-%%c')
```
