### ISSUE TITLE
Entity - oneSide does now working

### ISSUE THREAD

**Issue by f3l1x** [nextras/orm#178]
There is a note about `oneSide` in docs - https://nextras.org/orm/docs/2.0/relationships#toc-1-1-one-sided

But I always get this notice: `Modifier {1:1} in App\Model\ORM\Github\Github::$addon property has unknown arguments: oneSided`

**Comment by hrach** [comment]
Please provide the row with phpdoc definition.

**Comment by hrach** [comment]
Ping 😉

**Comment by f3l1x** [comment]
I'll try to find it (or maybe test it again). Give me some time. :-)

**Comment by hrach** [comment]
Closing for now, feel free to reopen :-)
