### ISSUE TITLE
New release - 2.0.x?

### ISSUE THREAD

**Issue by f3l1x** [nextras/orm#179]
I have used v2.0.2 on Componette but 1:1 (one sided) relation has been not correctly persistent.

I have to use dev-master. 

Can you please bump new version or tell me your roadplan? :-)

**Comment by f3l1x** [comment]
ping @hrach :-)

**Comment by hrach** [comment]
I'm really sorry, I'm getting maried in two weeks...  I will try to look at it asap.

**Comment by f3l1x** [comment]
No problem. I just wanna know what is the plan. :+1: Enjoy your wedding.

**Comment by hrach** [comment]
https://github.com/nextras/orm/releases/tag/v2.1.0-rc1
