### ISSUE TITLE
Apply filter on join table

### ISSUE THREAD

**Issue by Ejdems666** [nextras/orm#186]
Hi, is it possible to apply a filter on a join table in m:n relationship?
For example, I have these tables:

state(id,name) | state_organ(state_id,organ_id,year) | organ(id,name)

This is what I want using plain old SQL joins:
SELECT o.\* FROM
  state s
  JOIN state_organ so ON s.id = so.state_id
  JOIN organ o ON o.id = so.organ_id
WHERE so.year = 1 AND s.id = 1

The goal here is to have a collection of organ entities, that are in a relationship with a certain state in a certain year. And the "year" is a parameter in my join table state_organ.

Preferably I would like to have this as a virtual property in State entity.
Is there a nice way to do this?
Or do I have to iterate over a collection of StateOrgan entities and filter the Organ entities manually?

**Comment by hrach** [comment]
Sadly, currently it's not possible to filter hasMany relationships, because some aggregation is needed and that's not possible in repository leayer. But you may write custom sql/use query builder in mapper. See https://nextras.org/orm/docs/2.1/mapper

**Comment by hrach** [comment]
This is implemented as of https://github.com/nextras/orm/pull/376 and will be included in Orm 4.0.
You may read more about aggregation in https://blog.nextras.org/orm-4-aggregations/
