### ISSUE TITLE
ArrayCollectionHelper: invalid simplifyValue for DateTime

### ISSUE THREAD

**Issue by f3l1x** [nextras/orm#187]
Current solution is little bit stricky.

``` php
    private function simplifyValue($value)
    {
        if ($value instanceof IEntity) {
            return $value->hasValue('id') ? $value->getValue('id') : null;
        } elseif ($value instanceof \DateTime) {
                        ## HERE
            return $value->format('%U.%u');
        }
        return $value;
    }
```

If I compare date column by given DateTime object.

``` php
$collection->findBy('date=>', new DateTime());
```

Before comparing there is function `simplifyValue` called.

So that, the predicate lamda function compares badly.

``` php
        } elseif ($operator === ConditionParserHelper::OPERATOR_EQUAL_OR_GREATER) {
            $predicate = function ($property, $value) {
                return $property >= $value;
            };
        } elseif ($operator === ConditionParserHelper::OPERATOR_SMALLER) {
```
---

Current solution. It compares `string (scalar) => DateTime (object)`. 

![selection_003](https://cloud.githubusercontent.com/assets/538058/19698954/9f4d7916-9af1-11e6-8853-7f945daf0e5a.png)
---

Drop case for DateTime and let it as object. (`DateTime(object) => DateTime(object)`).

![selection_002](https://cloud.githubusercontent.com/assets/538058/19698950/9be45506-9af1-11e6-895e-acecc73f86b4.png)

**Comment by hrach** [comment]
Ha, this is currently a feature reqest. Entity does not support "date" anotation is it's your responsiblity to have the time "nulled". 

But, in Dbal, we should probably after reading a date from db set null hours:minutes:seconds. But it may not fix your usecase.

**Comment by f3l1x** [comment]
Hmm.. It's my fault, column is DateTime type, not date. But still issue is remaining.

**Comment by hrach** [comment]
> But, in Dbal, we should probably after reading a date from db set null hours:minutes:seconds. But it may not fix your usecase.

Yesterdays I've verified that Dbal's behavior is ok.

**Comment by f3l1x** [comment]
I don't thing that is dbal bad behavior. I thing that comparing is invalid, I mean `string >= object`.

**Comment by hrach** [comment]
Oh, I'd understood that the problem was in the time comparision. I will take a better look.

**Comment by f3l1x** [comment]
@hrach Thank you. :-)

**Comment by f3l1x** [comment]
Awesome! Thank you @hrach. :+1:
