### ISSUE TITLE
DateInterval not saved

### ISSUE THREAD

**Issue by SiViN** [nextras/orm#189]
Zdravim, v db (mysql) mam typ "time", v entite ji mam vedenou jako \DateInterval.
Nacitani funguje v pohode. Ukladani (naplneni entity) v poho, ale samotnej zapis do DB neprojde, vygeneruje se spatne sql:
`
$table->timeStart = new DateInterval($values->timeStart->format("\P\TH\Hi\M"));
$table->timeEnd = new DateInterval($values->timeEnd->format("\P\TH\Hi\M"));
UPDATE `table` SET `time_start` = 13:00:00, `time_end` = 14:00:00, ....
`
($values->timeStart, timeEnd jsou hodnoty z formu a jsou DateTime)
Delam neco spatne nebo je to bug?

**Comment by SiViN** [comment]
Uz jsem nasel ze to bylo opraveno v [https://github.com/nextras/dbal/commit/21271220538ee191ed4ca0038ca0745e01654cb2](url)

**Comment by hrach** [comment]
Oh, I see, I've forgot to release the new Dbal version. Thanks for the link!
