### ISSUE TITLE
QA: phpstan

### ISSUE THREAD

**Issue by f3l1x** [nextras/orm#208]
I could prepare PR if you want to.

**Comment by hrach** [comment]
This is something I'm strongly considering, the only dealbreaker is the fact, I'm not sure if it's already possible to use it as project, not as orm's depency. I would like to use it simillary as Parallel lint or Coveralls: https://github.com/nextras/orm/blob/1cc1f2464f15d45265bea1cbd5e59001eb8f4b58/.travis.yml#L32-L42

**Comment by Mikulas** [comment]
Do you mean phpstan extension for nextras, such as implementing `phpstan.broker.methodsClassReflectionExtension` for the `Repository : Mapper` method binding and other magic, or checking of this repository itself during CI?

**Comment by JanTvrdik** [comment]
> checking of this repository itself during CI

this one, imho

**Comment by hrach** [comment]
I mean I do not want to add it as composer's dependency.

**Comment by JanTvrdik** [comment]
@hrach Which I is BTW what I would do. I though about it while ago and came to the conclusion that considering how Composers currently works, installing tools (such as phpstan) via dev-dependency of the project is the best solution.

Installing via `composer create-project` makes it much harder to update the tool later and if you want to install optional dependency (e.g. phpstan/phpstan-nette) of the tool, then using `composer create-project` is especially hard and inconvenient.

**Comment by hrach** [comment]
See David's response - it's completly equal to my option.

**Comment by hrach** [comment]
Closed by ca1b527c51a0d9ec678d2c11bf95d9fa977a1c45

**Comment by f3l1x** [comment]
@hrach Thank you. Look's good.
