### ISSUE TITLE
QA: codesniffer

### ISSUE THREAD

**Issue by f3l1x** [nextras/orm#209]
I think it would be great to have some codestyle checking. The preparing of PR would be easier etc.. What do you think?

**Comment by hrach** [comment]
Actually, I don't like codestyle checking, or better, I have never the patience to configure it properly, since many rules are missing, many of them are specific, and many of them I want sometime intentionally violate.

**Comment by JanTvrdik** [comment]
Agreed, I have never seen codestyle checker configured properly. And codesniffer is piece of garbage.

**Comment by f3l1x** [comment]
I absolutely understand. I've been just curious. So closed up.
