### ISSUE TITLE
Order by null first/last

### ISSUE THREAD

**Issue by hrach** [nextras/orm#213]
Currently, orm doesn't unify null first/last behavior. In postgre there is different behavior than in mysql. What should be proper fix?

I would suggest:
- let ICollection::ASC be **internally** ASC_NULL_LAST and ICollection::DESC be **internally** DESC_NULL_LAST
- introduce new constants ICollection::ASC_NULL_FIRST and ICollection::DESC_NULL_FIRST.

Note: http://stackoverflow.com/a/8174026/859688

@JanTvrdik what do you think?

**Comment by hrach** [comment]
But, it's actually a BC break for array & mysql. :|

**Comment by JanTvrdik** [comment]
@hrach I agree with the suggestion. Maybe use `ASC_NULLS_LAST ` instead of `ASC_NULL_LAST` to be consistent with [PostgeSQL syntax](https://www.postgresql.org/docs/9.6/static/queries-order.html)?

**Comment by Mikulas** [comment]
👎 Orm should keep database defaults and not override them (when they are not objectively wrong eg for bc).

a/ Using Orm without knowledge of underlying DB is a pipe dream. Thus with this change users would need to know both DB and Orm behaviour.
b/ Documentation for DB is generally more thorough, includes performance tips etc, as it has more users.
c/ using the undocumented syntax (linked above) is a terrible idea as it may break in any future release, and it may already not work in maria or aurora.

👍 for the the query builder / collection constant, when the intended behaviour is explicitly requested by user
