### ISSUE TITLE
drop Nette object inheritance

### ISSUE THREAD

**Issue by hrach** [nextras/orm#232]
https://github.com/componette/componette/commit/cf32c3eb97f71156633ac5154512a3fda424cc6a

**Comment by JanTvrdik** [comment]
More importantly you CAN NOT load Nette\Object on PHP 7.2

**Comment by hrach** [comment]
done https://github.com/nextras/orm/commit/e44f13f1e1b6db20b0f5302ea9b60cbe79c080f7
