### ISSUE TITLE
Persist before remove action - null column problem

### ISSUE THREAD

**Issue by honzarac** [nextras/orm#235]
Hello,

I have problem with removing entity with not-nullable n:1 relationship.

Entities structure
```
/**
 * Episode
 * @property int $id {primary}
 * @property Project $project {n:1 Project::$episodes}
...
```
```
/**
 * Project
* @property int $id {primary}
 * @property Episodes[]|NULL $episodes {1:m Episode::$project}
...
```
and when I call `$this->orm->episodes->removeAndFlush($episode)` it throws **Nextras\Dbal\NotNullConstraintViolationException** Column 'project_id' cannot be null.
But I don't want persist this entity before removing.

Did I do something wrong?

**Comment by honzarac** [comment]
Can it couse persist after removing other connections in this entity?

**Comment by hrach** [comment]
Which version do you use? I think this may be fixed in master, hopefully also in v2.2 branch

**Comment by honzarac** [comment]
I tried 2.2.3 and 2.2.x-dev but it behaves same.

It is ok, when I remove other connected entities.

**Comment by hrach** [comment]
Could you please provide a testing zip? This behaviour seems to be covered by this test, where we are removing a book which has one author. https://github.com/nextras/orm/blob/master/tests/cases/integration/Entity/entity.remove.phpt#L28

**Comment by hrach** [comment]
@honzarac could send me a minimal repro? thanks :)

**Comment by honzarac** [comment]
Sorry I forgot. I'll send it tomorrow.

**Comment by hrach** [comment]
@honzarac ;)

**Comment by hrach** [comment]
Hi, I think I had randomly (re)discovered this bug and fixed it master :) Thanks for reporting.
