### ISSUE TITLE
Short open tag entiry problem

### ISSUE THREAD

**Issue by Vyki** [nextras/orm#236]
Hello,
On development server I obtained error:
`ReflectionException #-1
Class NextrasDemos\Datagrid\Project does not exist`
I was searching error in my code for 20 minutes, because everything looked OK, but then I found that I used short open tag `<?` instead of `<?php` in file with entity class. I fixed short open tag directive it in my development php.ini, but error with "does not exist" text is quite confusing.

**Comment by hrach** [comment]
This seems as wont-fix. We can't scan your directories for you and parse files for checking if you have used the corrent php open tag. The message is standard PHP error. I'm closing it because I had no idea how we can make this better, if you have some suggestion, feel free to comment.
