### ISSUE TITLE
Incomplete default configuration for DIRepositoryFinder

### ISSUE THREAD

**Issue by jkavalik** [nextras/orm#247]
When I tried to define the repositories in neon using
`repositoryFinder: Nextras\Orm\Bridges\NetteDI\DIRepositoryFinder` (v3.0 Beta)

I got some errors about missing `DbalMapperCoordinator` and `Nette\Caching\Cache` which I temporarily solved by adding
`orm.mapperCoordinator: Nextras\Orm\Mapper\Dbal\DbalMapperCoordinator`
and
`orm.cache: @<get our cache instance>`
to our services config.

These lines are not needed when using the "standard" `PhpDocRepositoryFinder` because it defines them as default.

**Comment by hrach** [comment]
- I've added auto adding od DbalMapperCoordinator
- the cache is already there, but is not autowired, so I added better example into the docs :)

**Comment by jkavalik** [comment]
Thanks, we use custom cache instance anyway :)
