### ISSUE TITLE
Custom repository names for DI repository definition

### ISSUE THREAD

**Issue by jkavalik** [nextras/orm#248]
We currently use custom property names for repositories in our ORM model to solve name possible clashes like
```
 * @property-read \Module1\Orm\SomeRepository    $some
 * @property-read \Module2\Orm\SomeRepository    $someOther
```

This seems not possible for repository-as-service used by DI loader because the repository name is derived from the class name which in this case leads to `Module2\Orm\SomeRepository` replacing `Module1\Orm\SomeRepository` in the model config (or the other way around depending on the definition order).

**Comment by hrach** [comment]
What is the usecase for having one repository registered twice?

**Comment by jkavalik** [comment]
It is not the same repository but two different repositories in two different namespaces which use the same classname. We created a system consisting of "modules" - for any instance only a subset of modules may be used. For example if we offer Articles, Galleries and Products. A gallery has multiple images, and a product may have multiple images - we have `GalleriesModule\Orm\ImagesRepository` and `ProductsModule\Orm\ImagesRepository` and we may just map one as $galleriesImages and the other as $productsImages in the model. That works with the PhpDoc repository definition but fails when using DI repository definition because only one $images property gets registered (referencing one of these two) and we get undefined repository for the Images association for either products or galleries and undefined for both `$orm->productsImages` and `orm->galleriesImages`.

We could just rename all the repositories etc. to make them unique, but it works like this currently and that feature of assigning a different name to the repository property on the model object got lost for this alternative method of mapping configuration.

**Comment by hrach** [comment]
Oh I see, this is definitelly a bug. Thanks for explanation.

**Comment by hrach** [comment]
Fixed in 3.0@dev :)

**Comment by jkavalik** [comment]
Thanks for a quick resolve. I implemented a bit different version for our usage if anyone is interested.
Extended the config with service name (prefix `repoAlias.` to not get clashes with any existing service):
```
services:
    repoAlias.gallItems: GalleryModule\Orm\GalleriesItemsRepository(GalleryModule\Orm\GalleriesItemsMapper(...))
    repoAlias.galGalleries: GalleryModule\Orm\GalleriesRepository(GalleryModule\Orm\GalleriesMapper(...))
```
and using the name where supplied:
```
$class = $serviceDefinition->getClass();
if(strpos($serviceName, 'repoAlias.') === false) {
    $name = lcfirst(str_ireplace('repository', '', substr($class, strrpos($class, '\\') + 1 ?: 0)));
} else {
    $name = str_replace('repoAlias.', '', $serviceName);
}
```

**Comment by hrach** [comment]
Hm, I will probably change it, le'ts pass service definition into getRepositoryName() method and add it by default under the DIC name.
