### ISSUE TITLE
SQL Server - duplicate data after persist

### ISSUE THREAD

**Issue by dyamon-cz** [nextras/orm#254]
Hello guys,

I'm currently testing Nextras/Orm with **sqlsrv driver** and I actually found issue immediately on beginning of my testing. Point is simple I've made just one entity and persist it into database, after look on data I can see two records of the entity what should have to be persisted only once.

I'm not sure if I did anything wrong but if I switch db to mysql everything works well. I'm using latest **nette/web-project**, **Nextras/Orm** **dev-master**, **Nextras/Dbal** **dev-master** and SQL Server 2012.

In my case is possible to find out this issue just with simple entity **Book**, **id {primary}** and **name**. In the database is identity(1,1) for primary key and varchar(50) for name. 

Interesting is that nette debug-bar is showing only one insert.

![debug-bar](https://user-images.githubusercontent.com/13029312/31760377-1873dfdc-b4e7-11e7-958b-a82c6aaa5942.png)

But I'm getting two records in the database.

![records](https://user-images.githubusercontent.com/13029312/31760424-38f9f174-b4e7-11e7-8a00-f8a497ef8373.png)

What is even more interesting and quite strange that when I put **unique key** on column **name** everything stay works well (no error that orm is trying to put two records to the table with unique key) and I even get just one record in the database.

Don't you have any idea what could be wrong?

Thank you very much!

_PS: Sorry for screens having different names (Book1, Book2) I captured it in different stage of testing._

**Comment by dyamon-cz** [comment]
OK guys, is because Debug Panel for Tracy, SqlsrvDriver::query (in Nextras/Dbal) is called two times when one of those queries is `EXPLAIN INSERT INTO [books] ([name]) VALUES ('Book 4')`. That's also the reason why tests can't show this bug.

**Comment by dyamon-cz** [comment]
This issue is possible to fix with configuration option for **Nextras/Dbal** `panelQueryExplain: false`

**Comment by hrach** [comment]
Hi, thanks for reporting! So the `EXPLAIN INSERT INTO [books] ([name]) VALUES ('Book 4')` actually inserts the row again?

**Comment by dyamon-cz** [comment]
Exactly, there is no such a thing like **EXPLAIN** in T-SQL syntax. So native client will throw error and execute rest of the query and because there is **try{ } catch{ }** in  ConnectionPanel::getPanel there will be no exception.

**Comment by hrach** [comment]
🤦‍♂️

**Comment by hrach** [comment]
Is it somehow possible to disable this behavior? (E.g. do nothing when there is an error -> exception).u

**Comment by dyamon-cz** [comment]
Here is the method...

```php
public function getPanel(){

    $count = $this->count;
    $queries = $this->queries;
    $queries = array_map(function($row) {
        try {
            $row[4] = $this->doExplain ? $this->connection->getDriver()->query('EXPLAIN ' . $row['1'])->fetchAll() : null;
        } catch (\Throwable $e) {
            $row[4] = null;
            $row[3] = null; // rows count is also irrelevant
        }

        $row[1] = self::highlight($row[1]);
        return $row;
    }, $queries);
    $whitespaceExplain = $this->connection->getPlatform()->getName() === 'pgsql';

    ob_start();
    require __DIR__ . '/ConnectionPanel.panel.phtml';
    return ob_get_clean();
}
```

Because I'm not really sure what is going to happen with the data which are obtained from **EXPLAIN** query I don't know how this can be fixed and don't affect some intentional functionality. Like I said before there is a property **doExplain** so I have put `panelQueryExplain: false` what completely skip that query execution. Even debug panel still works.

**Comment by hrach** [comment]
They are just rendered. I think this behavior must be caused by SQL server itself, or you you think it's just nextras' bug? I understood that as the problem of SQL server, which actually runs the query.

**Comment by dyamon-cz** [comment]
Oh yes that's actually quite wtf behavior of SQL server, you can try just simply run `EXPLAIN INSERT INTO [books] ([name]) VALUES ('Book 4')` in SQL Server Management Studio and you'll get this...
![eplain_query](https://user-images.githubusercontent.com/13029312/31775069-1fce47da-b51a-11e7-8149-d8501eda7a4b.png)

SQL Server understand this execution as it would be two separate statements so you will get error for **EXPLAIN** but **INSERT...** is going to be executed anyway. This is like standard SQL Server behavior. I don't know about any way how to change it.

**Comment by hrach** [comment]
Ok :) Thanks for verification. Will fix. :)
