### ISSUE TITLE
Bad query build for sufix 'Id' in column name

### ISSUE THREAD

**Issue by EchoZulu** [nextras/orm#259]
I have tables order_item and order.

```
`CREATE TABLE `order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `order_item` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orderId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idorder` (`order_id`),
  CONSTRAINT `order_item_ibfk_1` FOREIGN KEY (`orderId`) REFERENCES `order` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;`

```
And orm entities

```
/**
 * @property int $id {primary}
 * @property Order $order {m:1 Order::$items}
 */
class OrderItem extends \Nextras\Orm\Entity\Entity
{

}

/**
 * @property int $id {primary}
 * @property OrderItem[] $items {1:m OrderItem::$order}
 */
class Order extends \Nextras\Orm\Entity\Entity
{

}

```

Iterating over $order->items produce error, but if column name is changed from `orderId` to `order_id` everything works fine.

```
SELECT `order_item`.* FROM `order_item` AS `order_item` WHERE `order_item`.`order` IN (1)
Unknown column 'order_item.order' in 'where clause'
```

**Comment by hrach** [comment]
- these suffixes are stripped if there is a foreign key - you have it here, so it should work
- the actual strip strategy is depending if you are using underscored storage reflection or camelcase storage reflection, the first is the [default](https://github.com/nextras/orm/blob/b72194b61e3de6f929cd8b9ff81c14081a888f7b/src/Mapper/Dbal/DbalMapper.php#L231). are you sure you use the first one?
