### ISSUE TITLE
Nette 3.0 support?

### ISSUE THREAD

**Issue by Barbarossa-42** [nextras/orm#261]
nette/caching
nette/utils

**Comment by JanTvrdik** [comment]
The issue is that no stable version of a library can depend on unstable version of another library, meaning there cannot be stable version of nextras orm with support for unstable version of e.g. nette/utils 3.0.

**Comment by hrach** [comment]
I see, I thought that these are packages which have already the stable tag.

**Comment by Barabrossa** [comment]
Oh shit I need Nette 3.0 and this Orm 3.0. Is there any other hardcode way?

**Comment by hrach** [comment]
Why do you need Nette 3.0? There are some possibilites such as a fork, or some magic with version aliasing, but first, let's answer the reason why v3 or nette/caching and utils is so important :)

**Comment by Barabrossa** [comment]
If someone wants to start with new project he definitely use nette 3.0 and nextras/orm 3.0 - newest cool futures :) Such as junior programmer I have no chance how to use this cool features together (only wait for support).

**Comment by VaclavPavek** [comment]
Vhen are you planning to release the DEV version for Nette 3.0.0 when the RC version is already?

**Comment by hrach** [comment]
Hi guys, will take a look asap. Though, public communication the state of nette is terrible. Those who didn't attend posobota know nothing 😿

**Comment by hrach** [comment]
Done in #327 and in https://github.com/nextras/dbal/commit/d134a0628e1d184909bc4eee3efa3c42cc47fbb3
