### ISSUE TITLE
Add support for filtering by container property

### ISSUE THREAD

**Issue by hrach** [nextras/orm#262]
```php
/** @property Type $type {container TypeProperty} */
$collection->findBy(['type' => new Type()]);
```

**Comment by mrceperka** [comment]
I suppose, that `Type` should have `__toString()` which will return its value (for example stored in private property)

**Comment by hrach** [comment]
It should probably reuse IProperty::getRawValue()

**Comment by mrceperka** [comment]
Yep, that could do

**Comment by hrach** [comment]
If I've reviewed this feature request correctly, we need some converter method which will convert the passed argument to the raw value. Something like adding `IProperty::toRawValue()`.

This would actually also replace current [internal exceptions] for relationships:
- array collection: https://github.com/nextras/orm/blob/v3.0.0/src/Collection/Helpers/ArrayCollectionHelper.php#L130-L131
- dbal collection: https://github.com/nextras/orm/blob/v3.0.0/src/Mapper/Dbal/QueryBuilderHelper.php#L103-L104

Currently we have also hard-coded some support & conversions for datetime, but datetime is not intentionally implemented as container, because the memory & cpu overhead (the property is loaded everytime, relationship is not).

**Comment by mrceperka** [comment]
It seems that currently
```php
$collection->findBy(['type' => new Type()]);
// or 
$collection->findBy(['type' => (new Type())->getRawValue()]);
```
does not work properly on `ArrayCollection`.

`DbalCollection` can be `hacked` by ` (new Type())->getRawValue()`

**Comment by hrach** [comment]
Trying to implement now, but it's not as easy as I thought. 
Currently, the IProperty [is wired](https://github.com/nextras/orm/blob/v3.0.1/src/Entity/IProperty.php#L16) to entity -> therefore also IPropertyContainer is wired and there is no possibility to obtain IPropertyContainer instance which would allow conversion for a general call `$collection->findBy(['type' => new Type()]);`

Possible solutions: 

1) **Make the conversion method static.** - Most straightforward but with obvious drawbacks - the "static". It will disallow creating general containers which would configure themselves by PropertyMetadata, which is probably the most common usecase for EnumPropertyContainer.

2) **Refactor IProperty not to depend on IEntity** - Let's introduce other interface e.g. IEntityAwarePropertyContainer, but the general Property Container will be possible instantiate without entity and do conversion when needed. The question is how IEntityAwarePropertyContainer should works, if it is allowed to use it without entity initialization, or the general constraint is that it has to be usable without initialization for data conversion/normalization.

3) Some other solution.
