### ISSUE TITLE
v3.0.0-beta2 bug

### ISSUE THREAD

**Issue by Barabrossa** [nextras/orm#268]
Nette\DI\ServiceCreationException: Service 'orm.mappers.XXX': Service of type Nextras\Orm\Mapper\Dbal\DbalMapperCoordinator needed by Nextras\Orm\Mapper\Dbal\DbalMapper::__construct() not found. Did you register it in configuration file?

where XXX is name of first defined repository in Model. In previous version works fine.

**Comment by hrach** [comment]
Are you sure you have deleted a cache?
I see that Dbal's extension has to be defined first. Is it?

**Comment by Barabrossa** [comment]
Sorry it wasnt first. Thanks a lot.
