### ISSUE TITLE
Missing definition in OrmExtension for DbalMapperCoordinator

### ISSUE THREAD

**Issue by apincik** [nextras/orm#270]
OrmExtension setupDbalMapperDependencies() doesn't add DbalMapperCordinator if not presented in config file as service. Any future reason to specify this class in config ?

**Comment by hrach** [comment]
See: https://github.com/nextras/orm/issues/268
> I see that Dbal's extension has to be defined first. Is it?
Or try removing the cache.

**Comment by apincik** [comment]
Definition as first works well. Thanks

**Comment by hrach** [comment]
Will fix by a workaround :-)
