### ISSUE TITLE
Fix support for PHP 7.2 in Orm 2.2+ (Replace deprecated Nette\Object with trait Nette\SmartObject)

### ISSUE THREAD

**Issue by camohub** [nextras/orm#280]
Only for sure. I wrote about it on Slack. Exception occurred after composer update in ORM version 2,2 
Replace deprecated Nette\Object with trait Nette\SmartObject in vendor\nextras\orm\src\Model\Model.php:22

**Comment by f3l1x** [comment]
Could you please @hrach release a hotfix for 2.2 mainline? It cannot be used with newest nette/utils package.

**Comment by hrach** [comment]
It's quite shame that nobody created a PR. 😢 

Though, I'm doing the fix now...

**Comment by davidkregl** [comment]
Hi, I am just writing to ask how is it going with the fix? Are you working on it or should I create a PR?

**Comment by hrach** [comment]
Well, it was not so easy as it may seemed. Mainly because quite bad deprecation process in Nette.
Some progress is here, https://github.com/nextras/orm/commits/2_0_for_php_7_2
Not sure where I have left.

**Comment by milo** [comment]
In one of my library, I solved it in this piggy way:
```php
namespace Lib;
use Nette;

if (trait_exists('Nette\SmartObject')) {
	abstract class SmartObject
	{
		use Nette\SmartObject;
	}
} else {
	abstract class SmartObject extends Nette\Object
	{
	}
}
```

and all library classes extends `Lib\SmartObject`.

**Comment by davidkregl** [comment]
That is really piggy, @milo. 😀

**Comment by f3l1x** [comment]
Any progress @hrach? How can I help you?

**Comment by hrach** [comment]
> How can I help you?
Not sure, see https://travis-ci.org/nextras/orm/builds/351683091
IMO there is not well working combination of libs without hacks, if I remember correctly.
Also some bugs are probably present :/

**Comment by f3l1x** [comment]
I see only 

```
-- FAILED: Entity/Reflection/MetadataParserExceptionsTest.phpt [method=testOneHasMany]
   Failed: Nextras\Orm\InvalidArgumentException was expected but got Nextras\Orm\InvalidStateException (Entity NextrasTests\Orm\Entity\Reflection\EdgeCasesMetadataParserEntity1 does not have defined any primary key.) in testOneHasMany()
   
   in Entity/Reflection/MetadataParserExceptionsTest.phpt(82) Tester\Assert::throws()
   in [internal function]NextrasTests\Orm\Entity\Reflection\MetadataParserExceptionsTest->testOneHasMany()
   in src/Framework/TestCase.php(152) call_user_func_array()
   in src/Framework/TestCase.php(58) Tester\TestCase->runTest()
   in Entity/Reflection/MetadataParserExceptionsTest.phpt(125) Tester\TestCase->run()
```

That could be easy.

**Comment by hrach** [comment]
See other builds :/

**Comment by f3l1x** [comment]
Some trouble with countable.

**Comment by brada1703** [comment]
Does anyone have a fix for this?

**Comment by hrach** [comment]
@brada1703 please read the last comment, it ss ready in the branch v2.3, quite easy to require by composer, but nobody has responded, so it was not tagged yet.

**Comment by hrach** [comment]
Support for in branch, see https://github.com/nextras/orm/issues/280#issuecomment-406023186
Since no one was able to provide feedback, I'm not going to tag this for now.

**Comment by f3l1x** [comment]
Hi @hrach. 

I have included into contributte/datagrid and it works (https://travis-ci.org/contributte/datagrid/builds/507760278).

Maybe you can tag it now ;-)
