### ISSUE TITLE
Type 'Nextras\Dbal\Utils\DateTimeImmutable' in ... property is not supported 

### ISSUE THREAD

**Issue by Barabrossa** [nextras/orm#281]
To přeci není možné, abych po RC-2 dostal takový error nebo jo? Já ten Nextras\Dbal\Utils\DateTimeImmutable používám všude...

**Comment by hrach** [comment]
Je to mozne a je to prave fix toho, ze to nikdy tak "presne" nefungovalo, ale tvarilo se.

V RC2 te to nechalo klidne s takovou anotaci zit, ale realne ti to vracelo cisty DateTimeImmutable, napr. v pripade pouziti defaultu, nebo autokonverze ze stringu, apod. Pri vytazeni z db opravdu chodily entity tohoto typu.

Toto byl nejlepsi "security" fix pro stable release, byt chapu, ze z dlouhodobeho hlediska asi nic moc nemit moznost pouzit subtyp DateTimeImmutable.

Pokud je to pro tebe zasadni problem, prosim vydrz s RC2, muzeme tu zkusit neco vymyslet. 
Realne pouzivas "features" DateTimeImmutable z Dbalu?

**Comment by Barabrossa** [comment]
Díky za rozumné vysvětlení, zůstávám tedy u RC2.

Chápu obavy z bezpečnostních rizik. Zvážil bych zda nepřidat do konfigu nějaké optional allow pro extend DateTimeImmutable případně výčet povolených. Jinak díky za super ORM a práci kterou odvádíte. Ať se dál daří :)

**Comment by hrach** [comment]
Ono to neni tak bezpecnostni ve smyslu kradeze dat, ale ze proste tvuj ti crashne, protoze nedostane typ, ktery ti tvrdi phpdoc anotace, ze ti vrati, nekdy ti to proste vrati jiny typ. Zkusim to dnes poresit.

**Comment by hrach** [comment]
Please, check the master if it works for you :)

**Comment by Barabrossa** [comment]
Works fine. Thanks a lot :)
