### ISSUE TITLE
API reference documentation

### ISSUE THREAD

**Issue by hrach** [nextras/orm#288]
ApiGen is probably dead (version is slow (https://github.com/ApiGen/ApiGen/issues/1015)) and CodePub.io is dead too (mainly because of the referenced issue).

Tasks:
- how much it takes to generate nextras orm doc in ApiGen 5
- alternative of apigen?
- wire it into build/CI process

**Comment by f3l1x** [comment]
I like ApiGen a lot, but v5 is so slow. You're right.

**Comment by hrach** [comment]
Seems there is a fix for apigen, though the project is obviously dead. https://github.com/ApiGen/ApiGen/pull/1038
