### ISSUE TITLE
Entity: allow relationship defined only on one side

### ISSUE THREAD

**Issue by hrach** [nextras/orm#29]

**Comment by f3l1x** [comment]
I know it's a won't fix. But, any idea? I think it could be great.

**Comment by hrach** [comment]
Idea about what? But you are right, let's reopen it and move it to 1.2 :)

**Comment by f3l1x** [comment]
I like Nextras\Orm but I think this one is only ugly thing.. :smiley: 

We/you should fix this thing. What problems do you think could came across?

**Comment by hrach** [comment]
I have already mentioned one few comments above.

**Comment by f3l1x** [comment]
```php
/**
 * @property Comment[] {1:m Comment}
 */
class Post {}

class Comment {}
```

Is it the way you suggest? Remove required relation in Comment, but optional?

**Comment by hrach** [comment]
No, on the other side, as in the exaple above. The comment wrongly mention the "M" side, but it should be the otherwise.

**Comment by f3l1x** [comment]
And how IDE suggest you comments in Post? Through {virtual}?

**Comment by hrach** [comment]
@f3l1x in no way. This is not the good example on one sided relationship. This is typical usecase when it doesn't make sense.

**Comment by f3l1x** [comment]
I see. I guess you may have to change defined relation on both side but in case of 1:m not required. Does it make sence? Or do you have any other idea?

**Comment by hrach** [comment]
Sorry, I don't understand whad do you mean.

**Comment by f3l1x** [comment]
I have updated my previous comment.

**Comment by vitkutny** [comment]
@hrach exception při použití one sided relací
 > Nextras\Orm\InvalidModifierDefinitionException
Modifier {1:1} in Ytnuk\Menu\Entity::$title property has unknown arguments: oneSided.

opraveno úpravou `MetadataParser.php:307`
```php
			} else {
				$targetProperty = NULL;
				unset($args['oneSided']);
			}
```

**Comment by hrach** [comment]
Fixed. Thanks! I should write some tests... :)
