### ISSUE TITLE
DbalMapper::remove fails when entity has differently arranged primary properties compared to attributes in database storage

### ISSUE THREAD

**Issue by pavelkovar** [nextras/orm#296]
For example we have table _user_to_course_ with attributes: _user_id_, _course_id_ and _role_id_, and entity:

``` php
/**
 * @property-read array $id {primary-proxy}
 * @property Course|null $course {primary} {m:1 Course::$users}
 * @property User|int $user {primary} {m:1 User::$courses}
 * @property Role|string $role {primary} {m:1 Role::$users}
 */
class UserToCourse extends AbstractEntity
{
}
```

Then code snippet:

``` php
$found = $this->repository->getBy([
    'this->course->id' => 'course_1',
    'this->user->id' => '123',
    'this->role->id' => 'role_1'
]);

if ($found !== null) {
    $this->repository->removeAndFlush($found);
}
```

fails with exception:
```
Nextras\Dbal\QueryException

ERROR:  invalid input syntax for integer: "course_1"
LINE 1: DELETE FROM "user_to_course" WHERE "user_id" = 'course_1' AND "course_id" = 123 AND "role_id" = 'role_1'
```

When I change order of entity properties to match order of attributes in database storage then everything works as expected.

**Comment by hrach** [comment]
Hi, thank you for the detailed bug-report! I will take a closer look soon. In the mean time you may try dev-master. I think I've already fixed this, it's not only released in stable version:
https://github.com/nextras/orm/commit/64ed252c30cef247519803dd7131db264aaf6fa2

**Comment by pavelkovar** [comment]
Hi, unfortunately it doesn't work even on _dev-master_. Incorrect behavior is caused by [this line](https://github.com/nextras/orm/blob/master/src/Mapper/Dbal/DbalMapper.php#L359) since result of _getPersistedId_ is ordered by entity properties and result of _getStoragePrimaryKey_ is ordered by columns in database storage.

**Comment by hrach** [comment]
Fixed, thanks a lot. https://github.com/nextras/orm/commit/bad39470bcf690627e4179f9f29d8b67475bca32
