### ISSUE TITLE
Select by DateTime

### ISSUE THREAD

**Issue by romanmatyus** [nextras/orm#298]
Hello,

I use this repository method:

```php
$now = new DateTime;
return $this->findBy([
	'workShiftFrom<=' => $now,
	'workShiftTo>=' => $now,
])->orderBy('workShiftFrom', ICollection::ASC);
```

On localhost i receive correct SQL, but on production server is time modified ```-2 hours```.

## localhost

```sql
SELECT `work_days`.* FROM `work_days` AS `work_days`
WHERE (`work_days`.`work_shift_from` <= '2018-07-17 06:28:48.771743') AND
(`work_days`.`work_shift_to` >= '2018-07-17 06:28:48.771743')
ORDER BY `work_days`.`work_shift_from`
```

## production

```sql
SELECT `work_days`.* FROM `work_days` AS `work_days`
WHERE (`work_days`.`work_shift_from` <= '2018-07-17 04:28:48.771743') AND
(`work_days`.`work_shift_to` >= '2018-07-17 04:28:48.771743')
ORDER BY `work_days`.`work_shift_from`
```

```
dbal:
	connectionTz: +00:00
	driver: mysqli
```

PHP: date.timezone = Europe/Bratislava

**What all can be cause?** I don't know how find problem :disappointed: 

Thx

**Comment by hrach** [comment]
This is mainly "problem" in the Dbal and how it handles timezones. See docs (be aware changes in 3.0, so switch to 2.0, if needed) https://nextras.org/dbal/docs/3.0/datetime. 

To see what's happening:
- what's your Orm version?
- what's is server's MySQL working timezone? (probably the same as the server's)

**Comment by romanmatyus** [comment]
- nextras/orm 3
- How I detect MySQL working timezone?

```sql
SELECT EXTRACT(HOUR FROM (TIMEDIFF(NOW(), UTC_TIMESTAMP))) AS `timezone`
```

return ```2```

Screenshot from php app:

![image](https://user-images.githubusercontent.com/1110294/42816362-daddb4b8-89ca-11e8-8960-c9e2ecc6535b.png)

Production database: **Server version: 10.0.32-MariaDB-0+deb8u1 - (Debian)**

@hrach Thanks

**Comment by hrach** [comment]
Oh, I see, I missed your config, you manually set the connection tz to offset 0. 

Are you really sure you don't set this on localhost? IMO this is the issue.

(I guess you correctly use `timestamp` column type and Dbal converts the time to the connection working timezone, which is different to php's default - the diff is 2 hours.)

Also, please, check and provide info about the column type on server and on localhost. Eventually what returns `SHOW FULL COLUMNS FROM work_days`

**Comment by romanmatyus** [comment]
I'm sure, on production server it's ```connectionTz: +00:00```. I try too ```auto```, but it did not help.

On localhost (without problems) it's ```connectionTz: auto```.

At 99%, I'm sure this is a hosting problem. But I can't identify where exactly. On localhosts and other hostings it's everything ok.

![image](https://user-images.githubusercontent.com/1110294/42817455-745cdf76-89ce-11e8-9455-16a38a23e20c.png)

**Comment by hrach** [comment]
Ok, you use column without support for timezone handling. As for that, Dbal doesn't do any timezone handling for you [during formatting Datetime](https://github.com/nextras/dbal/blob/9ba238bbbedc69913f920be2d493d922dcf99d84/src/Drivers/Mysqli/MysqliDriver.php#L324). So the only questions is if the column is correctly detected as "datetime" (and gets dts modifier) [here](https://github.com/nextras/orm/blob/3377b1b4bdf9bb4e0bb1dff1ea5c6e26828e05a9/src/Mapper/Dbal/StorageReflection/StorageReflection.php#L297).

Also, if you set the "auto" for productions, what exactly is run in SET time_zone query??? Is it your PHP timezone?

**Comment by romanmatyus** [comment]
When I set ```auto``` for production, I receive Exception.

![image](https://user-images.githubusercontent.com/1110294/42884913-de5cc7de-8a9f-11e8-985e-ca8d09b4589f.png)

It's possible fix it without reconfiguring server? App running on shared hosting :disappointed:

**Comment by hrach** [comment]
For this we have `auto-offset`

**Comment by hrach** [comment]
So this behavior was pretty expected since you were using different connection timezone.
