### ISSUE TITLE
Working with views

### ISSUE THREAD

**Issue by mskocik** [nextras/orm#300]
I know orm cannot work with views, because storage has no primary key defined. Can you suggest how implement some workaround (I did not dig into code deeply, so thats the reason I ask first)? Or is it even possible?

**Comment by hrach** [comment]
Well, you may provide fake "storage reflection" to provide actually valuable info about the base table the view selects from.

Depends what is the nature of the view, it it do some joins, or just advanced filtering, ...
For the start I would try to override `DbalMapper.createStorageReflection()` to work with some other reflection. The most simple solution is to pass the original table name.
