### ISSUE TITLE
Support array of entities as argument for IN operator search

### ISSUE THREAD

**Issue by japlavaren** [nextras/orm#302]
I have code:
```
$pricelist->allPrices->get()->findBy(['tariff' => $tariffs]
```
and getting error:
```
Modifier %any expects value to be pretty much anything, TariffEntity given
```
in Price entity I have definition:
```
@property TariffEntity $tariff {m:1 TariffEntity, oneSided=true}
```
variable `$tariffs` is array of `TariffEntity`. 

I can guess that problem is that `PriceEntity` is m:1 so I can not pass array there. But is there any way how to load multiple items with multiple m:1 relations as one?

**Comment by hrach** [comment]
I would say this is a bug, you may try to pass just ids, it should work.
```php
$pricelist->allPrices->get()->findBy(['tariff' => array_map(function($t) { return $t->id; }, $tariffs)]);
```

**Comment by japlavaren** [comment]
```$pricelist->allPrices->get()->findBy(['tariff' => array_map(function($t) { return $t->id; }, $tariffs)]);``` you can use `array_column($tariffs, 'id');` it will do the same job and it is shorter and nicer
