### ISSUE TITLE
Access to relation id directly

### ISSUE THREAD

**Issue by japlavaren** [nextras/orm#304]
I have Entity with column `parentId`. Is possible to access directly to this column? I can call `->parent` but it will create new sql command. I was searching in documentation but can not find solution for this case.

**Comment by hrach** [comment]
yes, you get access the "raw value" get `getRawValue("parent")`

**Comment by japlavaren** [comment]
great. Is it mentioned in documentation or I just missed it?

**Comment by hrach** [comment]
I see it's documented here: https://nextras.org/orm/docs/3.0/entity so closing it. Though, it could be more visible... :)
