### ISSUE TITLE
Removing related entities 

### ISSUE THREAD

**Issue by japlavaren** [nextras/orm#305]
With code:
```
$author = $this->authorRepository->find(1);
$address = $author->address;
$author->address = null;
$this->addressRepository->remove($author->address);
$this->author->repository->persistAndFlush($author);
```
I am getting  **Cannot delete or update a parent row: a foreign key constraint fails** because orm is firstly deleting address entity than updating author. Expected behavior for me is reversed - first set null for author address and than address.

I know that I can use on cascade set null for author address foreign key, but I do not want to. I want to manage it manually.

**Comment by hrach** [comment]
Hm, this may be a bug,... the issue is that "remove" doesn't control if the "address" property is "modified" but not persisted. What is your case. If you would not modified it itself, the remove would do it for you and everything would be ok. Would you mind to try it?

**Comment by japlavaren** [comment]
I am not sure how you mean it. Can you write example here?

**Comment by hrach** [comment]
```php
$author = $this->authorRepository->getById(1);
$this->addressRepository->removeAndFlush($author->address);
```
should be sufficient

**Comment by japlavaren** [comment]
I have something similar and it is working

**Comment by hrach** [comment]
Ok, I have checked this and it is not a bug actually. With the proper testing code it may be more obvious.
```php
$book = $this->orm->books->getById(4);
$translator = $book->translator;
$book->translator = null;
// do not persist yet
$this->orm->remove($translator);
$this->orm->persistAndFlush($book);
```

By nulling translator in book->translator the connection between translator entity and book entity is lost. Book remain in the modified and unpersisted state. Calling remove without manual nulling helps, as mentioned earlier, or, you may switch the order or remove and persist to
```php
$this->orm->persist($book);
$this->orm->removeAndFlush($translator);
```
