### ISSUE TITLE
Value settings triggering isModified(property) even when value is same

### ISSUE THREAD

**Issue by marabucz** [nextras/orm#309]
Let's say you have entity `Entity` with property `$title` being equal to 'myTitle'. The problem is, if you attempt to set `$title` to `myTitle` again, isModified('title') is set to true.

It makes a sense ofc, as you're setting the property to something, however if the value is same is it used to be, I guess it shall be considered as false - so there are no triggers to persist methods etc. Ie the row https://github.com/nextras/orm/blob/master/src/Entity/AbstractEntity.php#L144

might look like `} elseif($this->data[$name] !== $value) {`

**Comment by JanTvrdik** [comment]
I think that's intentional and that the current behavior is better-

**Comment by hrach** [comment]
I know we have discussed this but I cannot remember the outcomes.

**Comment by hrach** [comment]
Let's say that this "intelligent" behavior may prevent from saving -> e.g. causing issues by not triggering an sql query -> triggering triggers etc.
