### ISSUE TITLE
SELECT DISTINCT in ORM

### ISSUE THREAD

**Issue by TOMeeeek** [nextras/orm#310]
Hello,
does ORM achieve the result as this?
`SELECT DISTINCT producers WHERE category IN(...)`
I tried a mapper, but no result.
Thank you

**Comment by hrach** [comment]
Use query builder or raw query in mapper layer, docs here: https://nextras.org/orm/docs/master/mapper#toc-dbalmapper
(I have to update it for 3.0, changes can be seen only in master doc for now)
