### ISSUE TITLE
Removing one of 1:n relationships throws an exception

### ISSUE THREAD

**Issue by 2bad2furious** [nextras/orm#316]
Hi, I have 2 entities connected by a table with 1:m and m:1 relationshipts, respectively.
```
@property-read int                $id                                           {primary}
@property-read OneHasMany         $ingredients                                  {1:m GoodsHasIngredient::$goods}
class GoodsEntity .... {}


@property-read int                   $id         {primary}
@property-read GoodsEntity           $goods      {m:1 GoodsEntity::$ingredients}
@property-read GoodsIngredientEntity $ingredient {m:1 GoodsIngredientEntity::$inGoods}
class GoodsHasIngredient ... {}

 
@property-read int            $id              {primary}
@property-read ManyHasMany    $inGoods         {1:m GoodsHasIngredient::$ingredient}
class GoodsIngredientEntity ... {} 
```

and calling `$this->ingredients->remove($hasIngredient);` in GoodsEntity
sets the HasIngredient::$goods to null, even though it is not nullable => throws an exception.

I temporarily fixed it by adding true as a second parameter inside the HasOne::setInjectedValue method like this 
```
public function setInjectedValue($value)
{
        $this->set($value, true);
}
```
This worked for my issue, but I am not sure about the implications for other cases.

**Comment by 2bad2furious** [comment]
Ok, turns out my fix did not fix anything, so I'll describe, what I did and and what should have happened in my opinion. I manually cloned the goods entity, cloned the goods_has_ingredient entites and then tried to remove some of those 'goods_has_ingredient's before they were even persisted, but the ORM was still trying to save the new 'goods_has_ingredient's after they were 'removed' (tried `$this->ingredients->remove($has_ingredient)` as mentioned above, and also `$this->getRepository()->getModel()->remove($has_ingredient)`); Both didn't work, changing the mentioned method only delayed the error, it crashed during persistence.

 I get, why the first call didn't succeed (kinda, in my opinion the ORM should check, that the fk is not nullable and remove the entity), the other should have succeeded, but the entity was to be persisted anyway.

**Comment by hrach** [comment]
Closing for now.
