### ISSUE TITLE
Typesafe/Non-nullable return-type of getById()

### ISSUE THREAD

**Issue by hrach** [nextras/orm#319]
We need to to find a name for `function <T> getById(): T` (e.g. function which checks for non-nullable result.) This will help to write type-safe code and avoid additional checks for PhpStan etc. 

It's generally impossible to do this by additional parameter, so we need to find another name. I was thinking about another prefix to `get` and `find`, but this seems to be quite complicated to come up with a good name. The get seems to be pretty good choice, but it would be a huge BC break. That's totally no-go.

The last option is a suffix and that's probably the best option, something like `getByIdAndCheck()`. 

Any other ideas? cc @JanTvrdik

**Comment by hrach** [comment]
Similar problem has been solved in Android Framework - old methods as `getActivity()`/`getParentFragment()`, which returned nullable object, received new sibling methods named with prefix `require` e.g. `requireActivity()`.

**Comment by hrach** [comment]
But specifically `require` would bring quite mess into the api. In the context of collection it would suggest some requirements for the condition.

**Comment by jtojnar** [comment]
I like `getByIdAndCheck()`.

Some other ideas:

* `getExistingById()` – does not really carry the checking connotation any more than the original name
* `getByIdStrict()` – might imply that the other method is lazy
* `getByIdOrThrow()`

**Comment by mabar** [comment]
`get` and `find` are nice names. Couldn't we have a new repository and collection classes for that? Something like StrictRepository seems less evil to me, as it is used only for extending and specific repostory classes are get from DI.

**Comment by hrach** [comment]
This should be definitely part of ICollection so it's quite difficult to do that like you've described. Also inheritance is not a good approach for implementing this.

**Comment by mabar** [comment]
You are right. I would prefer huge BC break, but also understand why you don't like it.

**Comment by hrach** [comment]
One more possibility:  change the current behavior and introduce `getByIdOrNull()`

**Comment by mabar** [comment]
Sounds good for me 👍

**Comment by hrach** [comment]
It is `getByIdChecked()` & `getByChecked()`
