### ISSUE TITLE
Set the value as SQL function in INSERET

### ISSUE THREAD

**Issue by masicek** [nextras/orm#330]
Hello,

is it some way how set the value od entity as sql function? For example if I have entity with integer property and I want to set them to `SUBSTRING(UNIX_TIMESTAMP(), 2)`. I want to set the value exactli in sql during inserting, not in PHP script.

Thanks

**Comment by JanTvrdik** [comment]
You can try overriding the [processInsert](https://github.com/nextras/orm/blob/e1799039e43556190c6abb145eec55cf8cf93fa8/src/Mapper/Dbal/DbalMapper.php#L277-L285) method in mapper

**Comment by masicek** [comment]
But how :-(. If I set the `$data['...']` the value `SUBSTRING(UNIX_TIMESTAMP(), 2)` was interpreted as string. I have no idea.

**Comment by hrach** [comment]
You may override fault Dbal's modifier in storage reflection. Try using [addModifier](https://github.com/nextras/orm/blob/e1799039e43556190c6abb145eec55cf8cf93fa8/src/Mapper/Dbal/StorageReflection/StorageReflection.php#L223)

**Comment by hrach** [comment]
With JanTvrdik's response you would have to change the key to append %raw to it. This method should do this for you.
