### ISSUE TITLE
Broken DIRepositoryLoader with nette\di 2.4.15

### ISSUE THREAD

**Issue by pavelmlejnek** [nextras/orm#333]
**Describe the bug**
Today released version of nette\di (2.4.15) broke DIRepositoryLoader, more specifically this commit is the cause: https://github.com/nette/di/commit/e82661f308dd3718f07f59f9717e79210f84e84c

I`d send a PR with a fix, but I wonder whether just casting serviceName to string is the best solution. If so, I can send a fix :-)

**Comment by hrach** [comment]
Fyi @davidgrudl

**Comment by hrach** [comment]
FYI @dg

**Comment by hrach** [comment]
@pavelmlejnek Thanks for the report. If I reviewed this correctly, the Model's string casting quickfix should be good. PR would be great :)

**Comment by pavelmlejnek** [comment]
DIRepositoryLoader counts on service name always being string, even the anonymous one, which was changed in latest nette/di and now causes TypeError.

**Comment by dg** [comment]
In fact, the name could be a number even before latest nette/di, when service was defined this way:

```
	-
		factory: PDO
```

**Comment by pavelmlejnek** [comment]
Sidenote: could you please release nextras/orm v3.0.3 with this fix, as this now requires a fix in composer.json to make an application using DIRepositoryFinder working?

**Comment by dg** [comment]
I think it is not BC break. Names can be number always and anonymous is still anonymous.

**Comment by dg** [comment]
In DI 3.0 names will be only strings https://github.com/nette/di/commit/267862e570e2650282ae2ad4763472a56947b662#diff-a46f14857c4aea27829419b9d1474390R65

**Comment by hrach** [comment]
Great! Thanks :)
