### ISSUE TITLE
Entity inheritance - how?

### ISSUE THREAD

**Issue by zener05** [nextras/orm#342]
Hello, I'm trying to have entity inheritance in Nextras\ORM but I'm not sucessfull.

Let's say I have main entity `Message` and there should be more inherited entites (`FacebookMessage`, `ChatMessage`, ...).

Can you help me how to design these entities and database, please? Thank you.

**Comment by hrach** [comment]
STI [is documented](https://nextras.org/orm/docs/3.1/entity-sti) Though, I would recommend using a composition instead of inheritance. Maybe you could more describe your troubles.

**Comment by zener05** [comment]
I've tried STI but it's not worked for me. My classes look like this (simplified)...

```php
/**
 * @property int $id {primary}
 * @property string $content
 * @property DateTimeImmutable $createdAt
 * @property string $type {enum self::TYPE_*}
 */
abstract class Message extends Entity
{
	const TYPE_CHAT = 'chat';
	const TYPE_FACEBOOK = 'facebook';
}


/**
 * @property-read string $type {default facebook}
 * @property string $facebookSenderId
 * @property string $facebookMessageId
 */
class FacebookMessage extends Message
{

}

/**
 * @property-read string $type {default chat}
 * @property string $sessionId
 * @property string $chatName
 */
class ChatMessage extends Message
{

}
```

My repository looks like this...

```php
class MessageRepository extends Repository
{

	public static function getEntityClassNames(): array
	{
		return [Message::class, FacebookMessage::class, ChatMessage::class];
	}

	public function getEntityClassName(array $data): string
	{
		switch ($data['type']) {
			case Message::TYPE_FACEBOOK:
				return FacebookMessage::class;
			case Message::TYPE_CHAT:
				return ChatMessage::class;
		}
		
		return '';
	}
}
```

When I call `$this->messageRepository->findAll()`, everything is OK and I really get array of `FacebookMessage` (there are only message of this type in DB yet). The problem is when I try to get property of `FacebookMessage`, e.g. `$message->facebookSenderId`. I get exception `Property app\model\Entity\FacebookMessage::$facebookSenderId is not set.`

**Comment by hrach** [comment]
So the column is not probably returned in the select. Please provide all info - which queries were executed, what is the structure of db, etc. See bug report template :)

**Comment by zener05** [comment]
You're right, column is not returned. ORM makes only one query - `SELECT * FROM messages`.

I think that there is a problem in DB scheme. I'm not sure how to design it. It looks like this now:

```sql
CREATE TABLE "message" (
    "id" integer serial,
    "content" text NOT NULL,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "type" character varying(20) NOT NULL
);

CREATE TABLE "facebook_message" (
    "message_id" integer NOT NULL,
    "facebook_sender_id" character varying(50) NOT NULL,
    "facebook_message_id" character varying(50) NOT NULL,
    CONSTRAINT "facebook_message_message_id_fkey" FOREIGN KEY (message_id) REFERENCES message(id) NOT DEFERRABLE
);
```

I don't know how to define connection between STI. Is the foreign key enough?

**Comment by hrach** [comment]
Ok, this is not an STI but MTI which is not supported. For read-only it could be hacked but persistence will be a problem.

**Comment by zener05** [comment]
That's bad 😕 But OK, I'll manage it different way. Thank you for your time and great ORM 👍
