### ISSUE TITLE
Prepojenie hlavnej tabuľky s vedľajšími

### ISSUE THREAD

**Issue by iGavrilo** [nextras/orm#345]
Zdravím,

chcel by som sa poradiť ako je možné spárovať vedľajšiu tabuľku s hlavnou.

Príklad:

Mám hlavnú tabuľku products a vedľajšiu tabuľku product_attachment kde mám nastavený product_id ako cudzí kľúč na products.id

Attachment pre product môže byť XN a neviem prísť na spôsob ako to inteligentne vytiahnuť.

Ďakujem

**Comment by hrach** [comment]
Jednoduse, mel by si mit na kazdou tabulku vlastni entitu a pak delat neco jako
```php
foreach ($productsRepository->findAll() as $product) {
    foreach ($product->attachements as $attachemenet) {
         // ....
    }
}
```

**Comment by iGavrilo** [comment]
Takže do ProductEntity stačí len pridať toto ? 
` * @property ProductAttachmentEntity $attachment {1:m ProductAttachmentEntity::$productId}`

čo potom pridať do ProductAttachmentEntity ?

**Comment by hrach** [comment]
U products je to vazba OneHasMany a u ProductAttachment  je to vazba ManyHasOne a je zdokumentovana v example: https://nextras.org/orm/docs/3.1/relationships#toc-1-m-m-1-bidirectional

Jinak se odkazujes na nazev sloupce a ty jsou u relationshipu automaticky bez Id suffixu.

**Comment by iGavrilo** [comment]
Ďakujem už rozumiem :)

**Comment by iGavrilo** [comment]
http://snpy.in/Uhmq8S

**Comment by hrach** [comment]
> $attachment teda nemusí reprezentovať stlpec v tabuľke ?

Ano, pokud je to na te strane, kde neni cizi klic. 

> nie su dáta

To uz jsem ti radil:
> Jinak se odkazujes na nazev sloupce a ty jsou u relationshipu automaticky bez Id suffixu.

Tzn. tu property musis pojemenovat i na ni se odkazovat bez suffixu.

**Comment by hrach** [comment]
Solved.
