### ISSUE TITLE
Custom SELECT causes Property is not set exception on later queries

### ISSUE THREAD

**Issue by novotnej** [nextras/orm#351]
Specifying a select() in the mapper 
```php
$q = $this->builder();
$q->select("video.id");
```
causes the ORM to cache information about the entity, that only includes the id, then when I run 

```php
$result = $this->findAll()->findBy(["id" => $ids])->fetchAll();

or

$v = $this->connection->query("SELECT * FROM video WHERE id IN(".implode(",", $ids).")");
foreach ($v->fetchAll() as $row) {
    $videos[] = $this->hydrateEntity($row->toArray());
}

or 

$result = $this->toCollection($this->builder()->select("video.*")->where("id IN %i[]", $ids));

```

I get a Property App\Model\Video::$title is not set. exception.
The Query from what I can tell is generated and executed just fine
```sql
SELECT * FROM video WHERE id IN(5378,979)
```
and the database returns valid results as well. When I remove the custom $q->select("video.id"), everything works as expected - but I need to fetch only IDs in a complex search, as it is significantly faster to get the remaining data only from IDs... 

**Versions::**
- Database: . MySQL 5.7.24
- Orm: [dev-master]
- Dbal: 3.1-dev

**Comment by novotnej** [comment]
Edit: 
When I don't fetch the search results (of which I only need the IDs) as a collection, rather than going through the connection:
$this->connection->queryByQueryBuilder($q)->fetchAll();

I can then get the full results from the second query.

**Comment by hrach** [comment]
> $q = $this->builder();
> $q->select("video.id");
> causes the ORM to cache information about the entity, that only includes the id, then when I run

Yes, Orm uses the Indentity Map pattern and this is a consequence.

If you need fetch just ids for some logic, just use plan connection and query. E.g. fetch first the ids and fetch the entities for requested ids, or do not fetch them at all if not needed.

**Comment by hrach** [comment]
So basically you already write the same thing in the comment. That's the correct solution.
