### ISSUE TITLE
Generate entity inject method calls in compile-time

### ISSUE THREAD

**Issue by mabar** [nextras/orm#357]
`DependencyProvider::injectDependencies()` calls `Container::callInjects()` which is slow - currently are through reflection found all inject methods and properties of every single entity (not for every class, but every instantiated object) and services are found through `Container::getByType()` which is much slower than `Container::getService()`. It also makes imposible to remove `$wiring` property from generated container. This property can take 1/3 of whole container, so only existence of it can slow down container initialization.

I suggest to reimplement `Container::callInjects()` in compile-time. Optimized callback with all inject method and properties calls would be generated and then applied to entity. It should improve performance for huge entities and mass operations.

I am willing to implement it myself, I just wanted to let you know about it.

@dg You may be also interested in such optimalization? I already removed tags and parameters from generated container in Modette, only wiring remains.

**Comment by dg** [comment]
If you know of any general optimization for nette/di, I'll be happy for it.

Btw why do you think that getByType() is slower than getService()?

**Comment by mabar** [comment]
It search inside a huge array of strings (4k lines in my case) for a service name and then call getService(). I want to get rid of this unnecessary step

**Comment by dg** [comment]
It doesnt search, it looks via key.

**Comment by hrach** [comment]
Closing, Nextras Orm provides proper interface for extensibility, not sure if anything complex should be included. Feel free to comment more.
