### ISSUE TITLE
How to write $this->findBy()->count() effectively?

### ISSUE THREAD

**Issue by pupitooo** [nextras/orm#373]
Hi,

I am solving problem with counting results. When I write
`$this->findBy([...])->count()`
it generates 
`SELECT * FROM table WHERE ...`
after that it fetch results and counts. 

It is not so clever. Is there any option how to do something like `->countBy([...])`?
It should generate
`SELECT COUNT(*) FROM table WHERE ...`

It seems to me like important thing of ORM, so I thing there is some solution to do it.

Thanks for any help.

**Comment by hrach** [comment]
Use `countStored()`, documented here https://nextras.org/orm/docs/3.1/collection#toc-counting :)
