### ISSUE TITLE
Problem with basic filtering findBy/getBy

### ISSUE THREAD

**Issue by honzarac** [nextras/orm#382]
**Describe the bug**
I have problem with basic filtering. When I try to filter according id I get exception `Override Planovac\Model\Orm\ActorsRepository::createCollectionFunction() to return an instance of id collection function`.
Each repository throws this exception. It is kindly weird because this case is tested and I defined model, entity, repository like you in tests.

**To Reproduce**
Call  `$repository->findBy(['id' => 2]);`
Entity definition:
```
use Nextras\Orm\Entity\Entity;
use \DateTimeImmutable;
use Nextras\Orm\Relationships\ManyHasMany;

/**
 * Actor
 * @property int $id {primary}
 * @property string $name
 * @property Ensemble[]|ManyHasMany|null $ensembles {m:m Ensemble::$actors}
 * @property Role[]|ManyHasMany|null $roles {m:m Role::$actors, isMain=true}
 * @property DateTimeImmutable $created {default now}
 */
class Actor extends Entity
{
}    
```

Repository definition
```
use Nextras\Orm\Repository\Repository;
    
class ActorsRepository extends Repository
{
	static function getEntityClassNames(): array {
		return [Actor::class];
	}
}
```

**Expected behavior**
Function filter rows by id.

**Versions::**
 - Database: PostgreSQL 
 - Orm: Orm 3.1
 - Dbal: Dbal 3.1.1

**Comment by hrach** [comment]
This is pretty weird, this is of course tested. 
- are you sure you are using stable version?
- could you please provide exception stack trace?

**Comment by honzarac** [comment]
😮 now it works

I downgraded Orm to 3.0.3 (it throws same exception)
then I upgraded back to 3.1 and dumped cache and now it works.

Sorry, maybe it was my fault but I have no idea what was wrong.

**Comment by hrach** [comment]
Seems pretty weird :-O This functionality is pretty basic since that's how `getById()` is implemented.
https://github.com/nextras/orm/blob/98a11b9521f1865636a637ce5d6ca657d2d81250/src/Collection/DbalCollection.php#L68-L88

Closing, feel free to ask to reopen with more details.
