### ISSUE TITLE
Support PostgreSQL 12

### ISSUE THREAD

**Issue by honzarac** [nextras/orm#383]
**Describe the bug**
ORM does not support PostreSQL v12.1. When I try to execute some command I get exception

```
ERROR:  column ad.adsrc does not exist
LINE 8:     coalesce(co.contype = 'p' AND strpos(ad.adsrc, 'nextval'...
```

**To Reproduce**
Execute some command on ORM with PostreSQL 12.1

**Versions::**
 - Database: PgSQL 12.1
 - ORM: 3.1

**Comment by hrach** [comment]
This is an issue of dbal which has been fixed in master. https://github.com/nextras/dbal/pull/85
Will release stable asap.

**Comment by honzarac** [comment]
I was not shure if it is issue of orm or dbal. But it is great new. Thank you for your great support!

**Comment by hrach** [comment]
Relased 3.1.2 & 3.0.2
https://github.com/nextras/dbal/releases/tag/v3.1.2
