### ISSUE TITLE
remove & flush affecting count

### ISSUE THREAD

**Issue by jtojnar** [nextras/orm#385]
I have a code that is [removing](https://github.com/jtojnar/entries/blob/d7aafb7bbf06f1508729e2bf4b60e0687be57c4a/app/presenters/TeamPresenter.php#L348-L354) team members ([basic `m:1`](https://github.com/jtojnar/entries/blob/4a79bad0e0fa2a24e882b358b6338c960141580e/app/model/orm/team/Team.php#L24)) when editing a team and then [adding](https://github.com/jtojnar/entries/blob/d7aafb7bbf06f1508729e2bf4b60e0687be57c4a/app/presenters/TeamPresenter.php#L377-L384) new ones with the changed data. I was also [counting](https://github.com/jtojnar/entries/blob/d7aafb7bbf06f1508729e2bf4b60e0687be57c4a/app/presenters/TeamPresenter.php#L438) them afterwards but the `count($team->members)` was returning 0.

I managed to fix that by [cleaning up the flushes](https://github.com/jtojnar/entries/commit/2b24e81a997c53308689b64f81abd70edd8302f1) from the previous mess but I do not actually understand why does that happen.

I managed to pinpoint it to this `flush` https://github.com/jtojnar/entries/commit/d7aafb7bbf06f1508729e2bf4b60e0687be57c4a but that still should not affect the count. I would expect that to reflect even unpersisted changes.

**Comment by jtojnar** [comment]
Forgot I was also using `count` before persisting the new item. It almost looks like the latter count returns the count that should be returned by the first one and vice versa.

Managed to reproduce it in the testcase: https://github.com/nextras/orm/pull/386

**Comment by hrach** [comment]
Fixed by #395 and released in 3.1.1.
