### ISSUE TITLE
StorageReflection::findManyHasManyPrimaryColumns does not respect different database name

### ISSUE THREAD

**Issue by radimvaculik** [nextras/orm#387]
**Describe the bug**
Let's have 3 tables - `user`, `tag` and `user_x_tag` in database named `b`. If my default database name is `a`, then function `StorageReflection::findManyHasManyPrimaryColumns` throws an exception.

**To Reproduce**
TBD

**Expected behavior**
TBD

**Versions::**
 - Database: MariaDB 10.3
 - Orm: 3.1
 - Dbal: dev-master

**Comment by hrach** [comment]
Are the tables defined with FQN in Dbal?

**Comment by radimvaculik** [comment]
Yes, of course. `User` table for example.

```php
class UserMapper extends Mapper
{
    protected $tableName = 'b.user';
}
```

**Comment by hrach** [comment]
Hi, in Nextras Orm 4.0 this should be fixed by https://github.com/nextras/orm/pull/405.
Could you please test if this works for you? Thank.

**Comment by hrach** [comment]
Closing, please ask for reopen when still an issue.
