### ISSUE TITLE
v4.0 breaking changes documentation

### ISSUE THREAD

**Issue by mskocik** [nextras/orm#388]
Wanted to try the new collection functions, but it seems there will be some breaking changes in v4. Is the changelog already available somewhere, what has changed?

I get error for: 
```
User Deprecated
Property modifier {container} is depraceted; rename it to {wrapper} modifier
```

Intellisense is reporting no longer existing method `parent::createStorageReflection()` in extended Mapper classes.

**Comment by hrach** [comment]
done: https://nextras.org/orm/docs/4.0/migrate_4.0
