### ISSUE TITLE
Traversing through filtered relationships

### ISSUE THREAD

**Issue by hrach** [nextras/orm#39]
It would be nice to add api & possibility to filter & travers by filtered relationships. Such as

``` php
/**
 * @property      Comment[] $allComments {1:m CommentsRepository}
 * @property-read Comment[] $comments {filter $allComments}
 */
class Post extends Entity
{
    public function filterComments(ICollection $collection)
    {
        return $collection->findBy(['deletedAt' => NULL]);
    }
}

// find all posts which were commented by lord Stark
// and these comments weren't deleted.
$this->orm->posts->findBy(['this->comments->author' => $lordStark->id]);
```

**Comment by f3l1x** [comment]
Mmmm, it looks great. 

It could be common filter conception - like in LeanMapper.

http://forum.dibiphp.com/cs/14592-lean-mapper-tenke-orm-nad-dibi?p=3#p105447

**Comment by hrach** [comment]
Filters over relationship in properties were removed (and probably not even released). This concept is currently supported by [collection functions](https://nextras.org/orm/docs/3.0/collection-functions).
