### ISSUE TITLE
PhpDoc: nullable & more complex expressions

### ISSUE THREAD

**Issue by marabucz** [nextras/orm#394]
As PHP 7.4 came with typed properties, what about allowing us to write 

`* @property ?DateTimeImmutable $born  {default now}`
instead of
`* @property DateTimeImmutable|null $born  {default now}`

Or is there any reason why not (e.g. too complex parsing or something)?

**Comment by hrach** [comment]
Great issue, yes, we should do this :)

**Comment by hrach** [comment]
Also missing intersection type support for relationships.
