### ISSUE TITLE
Doubled database query

### ISSUE THREAD

**Issue by TonnyJe** [nextras/orm#399]
**Nextras make 2 identically queries to database**
If I use _->findAll()_ in foreach, then Nextras will make the same query more than once.

**To Reproduce**
Steps to reproduce the behavior. It could include:
Code:
`
foreach ($orm->users->findAll() as $user) {
    foreach ($user->gifts as $gift) {
        bdump($user->name . ' si přeje ' . $gift->name);
    }
}
foreach ($orm->users->findAll() as $user) {
    foreach ($user->gifts as $gift) {
        bdump($user->name . ' si přeje ' . $gift->name);
    }
}
`
User entity:
`
/**
 * @property int                $id         {primary}
 * @property string             $name
 * @property string             $password
 * @property string             $email
 * @property OneHasMany|Gift[]  $gifts      {1:m Gift::$user}
 */
class User extends Entity 
{
}
`
Gift entity:
`
/**
 * @property int    $id     {primary}
 * @property string $name
 * @property double $price
 * @property User   $user   {m:1 User::$gifts}
 */
class Gift extends Entity 
{
}
`
Table definitions:
**CREATE TABLE IF NOT EXISTS `gifts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `name` varchar(255) CHARACTER SET latin1 NOT NULL,
  `price` double NOT NULL,
  PRIMARY KEY (`id`),
  KEY `gift_ibfk_1` (`user_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;**
**DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET latin1 NOT NULL,
  `password` varchar(255) CHARACTER SET latin1 NOT NULL,
  `email` varchar(255) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;**

Executed queries:

- SET sql_mode = 'TRADITIONAL'
- SET time_zone = 'Europe/Prague'
- SELECT `users`.* FROM `users` AS `users`
- SELECT `gifts`.* FROM `gifts` AS `gifts` WHERE `gifts`.`user_id` IN (1, 2)
- SELECT `users`.* FROM `users` AS `users`

**Expected behavior**
If I use command ($orm->users->findAll()) out of foreach, then it is okay. So query wil execute only once. But in foreach that query will be executed once for each foreach.

**Versions::**
 - Database: MariaDB 10.4.10
 - Orm: Orm 3.1
 - Dbal: Dbal 3.1

**Comment by hrach** [comment]
That's intentional. Nextras Orm does not cache "query" results, only uses an identity map.

**Comment by TonnyJe** [comment]
Oh sorry i thought this:

`$users = $orm->users->findAll()->fetchAll(); $users2 = $orm->users->findAll()->fetchAll(); $users3 = $orm->users->findAll()->fetchAll();`

**Comment by hrach** [comment]
It do 3 queries, just tested, see carefully the query log.

**Comment by TonnyJe** [comment]
Okay. So please where I have bug in my code? [Image of log](https://pasteboard.co/J2rvZiN.png)

**Comment by hrach** [comment]
🤔 This is really weird. Could you please try checking query method in MysqliDriver? (e.g. dumping sql before executing), if there will be more these calls?
