### ISSUE TITLE
Call to a member function convertEntityToStorageKey() on null

### ISSUE THREAD

**Issue by honzarac** [nextras/orm#403]
**Describe the bug**
Mapper throws me an exception when I try to remove some entity. The bug appeared with the version 3.1.

**To Reproduce**
```
$this->orm->repo->remove($this->orm->repo->getById(10));
```

The problem is probably in DbalMapper line 365. It works with `$this->getStorageReflection()` instead of `$this->storageReflection`.

Tracy: [convertEntityToStorageKey_bug_tracy.zip](https://github.com/nextras/orm/files/4464998/convertEntityToStorageKey_bug_tracy.zip)

**Versions::**
 - Database: mariadb 10.0
 - Orm: 3.1.1
 - Dbal: 3.1.2

**Comment by hrach** [comment]
Thanks, this is only 3.1 issue, fixed there :)

**Comment by hrach** [comment]
Released as 3.1.2: https://github.com/nextras/orm/releases/tag/v3.1.2
