### ISSUE TITLE
Why MTI is not supported?

### ISSUE THREAD

**Issue by TonnyJe** [nextras/orm#417]
I have a problem that is perfectly solved by MTI (Multiple Table Inheritance). But I learned from [this](https://github.com/nextras/orm/issues/342) issue that NextrasORM does not support MTI.

Is there a fundamental reason for this? Or is it planned support MTI for the future versions?

**Comment by hrach** [comment]
Basically:
- because it's complicated to implement
- because I never needed this, or better I was satisfied with other options

Though I recognize the use-case, we usually used something like:

```
posts(*id, post_article_id, post_album_id, created_at)
post_articles(*id, title, url, perex, preview_img_url)
post_albums(*id, title)
post_life_event(*id, who_id, what, whom_id)
```
And then working simply

```php
$post = new Post()
$post->article = new PostArticle();
```

Could you describe your use-case?

**Comment by hrach** [comment]
> Is there a fundamental reason for this? 

Actually not sure, I didn't verify this.

> Or is it planned support MTI for the future versions?

Not on radar (for now?)

**Comment by TonnyJe** [comment]
My use-case is something like this:
I try biuld an e-shop database, where i have different products:

CREATE TABLE `product` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `price_in_cents` int  NOT NULL,
  `product_type` varchar(255) NOT NULL -- maybe enum??
) ENGINE='InnoDB';

But every product has different settings so:
CREATE TABLE `product_computer` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `processor` varchar(255) NOT NULL, --maybe foreign key to table with processors
  `graphics` varchar(255) NOT NULL, -- like previous line
  `ram_size` int  NOT NULL
) ENGINE='InnoDB';

CREATE TABLE `product_car` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `engine` varchar(255) NOT NULL, --maybe foreign key to table with engines
  `transmission_type` varchar(255) NOT NULL,
  `max_speed` int  NOT NULL,
  `wheel_size` int  NOT NULL
) ENGINE='InnoDB';

CREATE TABLE `product_cosmetics` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `type` varchar(255) NOT NULL -- for example tooth paste, tampoons etc (maybe enum?)
) ENGINE='InnoDB';

And so on. There can be N tables. Lets say, that my E-shop has 100 different products and I want to add more. 


But every single product must be specified in invoice

so I have theese tables:

CREATE TABLE `invoice` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `date_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `number` int NOT NULL
) ENGINE='InnoDB';

CREATE TABLE `invoice_item` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `invoice_id` int NOT NULL,
  `product_id` int NOT NULL,
  FOREIGN KEY (`invoice_id`) REFERENCES `invoice` (`id`) ON DELETE RESTRICT,
  FOREIGN KEY (`product_id`) REFERENCES `product` (`id`) ON DELETE RESTRICT
) ENGINE='InnoDB';


This directly encourages the use MTI.

**Comment by hrach** [comment]
Thanks for providing example. I would recommend using 1:1 relationship for your current schema, you will safe non-needed data fetching.

Currently I do not plan to implement so I will close. Thanks for understanding.
