### ISSUE TITLE
Error in findById function

### ISSUE THREAD

**Issue by TonnyJe** [nextras/orm#418]
**Describe the bug**
Hey. When I try something like this: _$this->model->users->findById($id);_

I got error **Custom function Nextras\Orm\Repository\Functions\ConjunctionOperatorFunction has to implement IQueryBuilderFilterFunction interface.**

**To Reproduce**
Steps to reproduce the behavior. It could include:
1. Code which you run: _$this->model->users->findById($id);_
2. Definition of entities:
```
/**
 * @property-read int           $id         {primary}
 * @property string             $email
 * @property string             $password
 * @property string             $fullName
 */
class User extends Entity {}
```

**Versions::**
 - Database: MariaDB 10.4.10
 - Orm: "nextras/orm": "^3.1"
 - PHP: 7.3.12
 - Apache: 2.4.41

**Comment by hrach** [comment]
Hi, as you can see, the [class implements that interface](https://github.com/nextras/orm/blob/v3.1/src/Repository/Functions/ConjunctionOperatorFunction.php#L20). Such error is also weird since it is a core-functionality. Could you please provide the stacktrace?

**Comment by hrach** [comment]
@TonnyJe could you please provide more info?

**Comment by TonnyJe** [comment]
No, because I already used NDBT instead, so I don't have this code anymore.
