### ISSUE TITLE
When we are getting stable v4 ? Where's the doc?

### ISSUE THREAD

**Issue by farhanianz** [nextras/orm#426]
Well, I would like to give a try on my new project, It will be a new experience for me as I never used Nextras ORM before. But currently the nextras.org has the v3.1 docs available, as I just found out that there's gonna be a v4, I thought I should learn & use the latest one instead.

So, some questions please,

- When we are getting stable v4 ? 
- Where's the doc?
- BC break? Will there be a deep learning curve if I learn v3.1?

**Comment by hrach** [comment]
>  I thought I should learn & use the latest one instead.

Yes, I recommend starting with v4.

> When we are getting stable v4 ?

RC will be this month. Stable will follow, possible in month or two.

> Where's the doc?

It's currently available as "master". https://nextras.org/orm/docs/master/
Though, more doc should be created.

> BC break?

There will be BC breaks but probably not for a novice.

> Will there be a deep learning curve if I learn v3.1?

Hopefully not. As always, a migration guide will be published. Still, I recommend start with v4.

**Comment by hrach** [comment]
If you have any further questions, feel free to ask.
