### ISSUE TITLE
'array_combine() expects parameter 2 to be array, int given' when fetching collection with composite primary key

### ISSUE THREAD

**Issue by Hologos** [nextras/orm#448]
**Describe the bug**

I get _**TypeError: array_combine() expects parameter 2 to be array, int given**_ when fetching collection with composite primary key.

[Trace file](https://github.com/nextras/orm/files/5086547/trace.html.zip)

**To Reproduce**
```php
<?php

declare(strict_types=1);

namespace App\Model;

use Nextras\Orm\Entity\Entity;
use Nextras\Orm\Relationships\ManyHasMany;

/**
 * @property int                      $id                    {primary}
 * @property string                   $email
 * @property ManyHasMany|Benefit[]    $benefits              {m:m Benefit::$customers, isMain=true}
 */
class Customer extends Entity
{
}

/**
 * @property int                      $id          {primary-proxy}
 * @property int                      $category    {enum self::CATEGORY_*} {primary}
 * @property int                      $type        {enum self::TYPE_*} {primary}
 * @property string                   $name
 * @property ManyHasMany|Customer[]   $customers   {m:m Customer::$benefits}
 */
abstract class Benefit extends Entity
{
    const CATEGORY_DAILY_MENU_ITEM_PRICE = 2;

    const TYPE_ALL_DISHES_FOR_FREE = 2;
}

foreach($this->customer->benefits as $benefit)
{
    \Tracy\Debugger::dump($benefit->category .' '. $benefit->type);
}
```

**Expected behavior**
Be able to fetch collection.

**Versions::**
 - Database: mysql  Ver 8.0.21 for osx10.15 on x86_64 (Homebrew)
 - Orm: 3.1.3
 - Dbal: 3.1.2

**Comment by hrach** [comment]
This is not a bug, but unsupported feature, not currently planned.
_Orm does not support multi-column foreign keys._

If you need only one combination of category & type, put there artificial auto-increment id and make category & type an unique key.

**Comment by Hologos** [comment]
The problem is that I need combination of `customer_id` + `category` + `type` to be unique. I will have to do it using two `1:m` relationships as you proposed on slack.

**Comment by hrach** [comment]
If category+type is unique, than id of this row is unique. Thank the connection table for m:m can be has unique entries to, since customer_id and benefit_id will be part of PK.
