### ISSUE TITLE
Migration to 4.0: Missing IArrayFilterFunction, IQueryBuilderFilterFunction migration

### ISSUE THREAD

**Issue by radimvaculik** [nextras/orm#458]
Missing information about migration IArrayFilterFunction & IQueryBuilderFilterFunction @ https://github.com/nextras/orm/blob/master/doc/migrate_4.0.texy

**Versions::**
 - Orm: 4.0
 - Dbal: 4.0

**Comment by hrach** [comment]
There is this note:

> Collection: reworked custom collection functions
> Custom functions have been completely reworked and simplified, see docs what they can do now and how to write them.

I may add few more words but generally there is not way how to provide migration path. You should read the new docs and rewrite according to it.

**Comment by hrach** [comment]
@radimvaculik if you would like, you could help me what was the main change for you, I will write it into doc :)

**Comment by radimvaculik** [comment]
@hrach All good. I missed the note. Maybe, you should provide more information, who classes change the names. For example:
 * `IArrayFilterFunction` ▶️ `IArrayFunction`
 * `IQueryBuilderFilterFunction` ▶️ `IQueryBuilderFunction`
 * new return value for `processQueryBuilderExpression` - `array` ▶️ `DbalExpressionResult`

**Comment by hrach** [comment]
thanks, will add :)
