### ISSUE TITLE
PHPDoc relationships's orderBy is inconsistent

### ISSUE THREAD

**Issue by radimvaculik** [nextras/orm#460]
Ahoj, jen takove zamysleni k `orderBy` priznaku. Zazil jsem takovy mindfuck a v dokumentaci to neni uplne zrejme.

Pokud chci radit podle jednoho sloupce, tak staci `orderBy=[id]`, anebo vlastne staci `orderBy=id` pokud chci radit opacne, staci pridat `orderBy=[id, DESC]`. Ale pokud chci radit podle dvou sloupcu, uz nestaci `orderBy=[id, name]` ale musim to zapsat jako `orderBy=[id=ASC, name=ASC]`. 

Uprimne bych zrusil moznost radit timto zpusobem - `orderBy=[id, DESC]`.

**Comment by radimvaculik** [comment]
A jeste zminky v dokumentaci k `orderBy`, ktere se taktez rozchazi:

https://nextras.org/orm/docs/4.0/relationships
```
{1:m EntityName::$reversePropertyName, orderBy=property}
{m:m EntityName::$reversePropertyName, isMain=true, orderBy=[property=DESC, anotherProperty=ASC]}
```

https://nextras.org/orm/docs/4.0/
```
 * @property OneHasMany|Book[]      $books {1:m Book::$author, orderBy=[id, DESC], cascade=[persist, remove]}
```

**Comment by hrach** [comment]
I've reviewed this and it makes sense a little, but I'm ok with changing this. Probably will deprecate the `orderBy=[id, DESC]`. But I don't see it as some critical thing we should push forward asap, so this will probably get into 5.0.
