### ISSUE TITLE
PHP 8.0: attributes in Orm's Entity

### ISSUE THREAD

**Issue by hrach** [nextras/orm#470]
_This issue opens a discussion if Orm could utilize attributes for entity definition, and if so, how exactly._

**The new attribute-supported entity may be a brand new implementation of IEntity, allowing no-BC breaks.**

------

**Current state:**

```php
/**
 * @property int|null               $id           {primary}
 * @property string                 $title
 * @property Author                 $author       {m:1 Author::$books}
 * @property Author|null            $translator   {m:1 Author::$translatedBooks}
 * @property MHM&Tag[]              $tags         {m:m Tag::$books, isMain=true}
 * @property DateTimeImmutable      $publishedAt  {default now}
 * @property Money|null             $price        {embeddable}
 */
class Book extends Entity {}
```

------

**Use class annotations**

```php
#[Property("id", "int|null",Primary())]
#[Property("title", "string")]
#[Property("author", Author::class, ManyHasOne(Author::class, "books")]
#[Property("translator", Author::class . "|null", ManyHasOne(Author::class, "translatedBooks")]
#[Property("tags", "MHM&Tag[]", ManyHasMany(Tag::class, "books", isMain: true)]
#[Property("publishedAt", DateTimeImmutable::class, Default("now"))]
#[Property("price", "Money|null", Embeddable())]
class Book extends AttributeEntity {}
```

Pros:
- partially type-safe definition (properties of modifiers)
- better IDE support (no plugin required for highlighting)

Cons:
- property type has to be somehow constructed; (other possibilities?)
- IDE plugin still required to provide completion, at least for types defined as string

------

**Move to properties**

```php
class Book extends AttributeEntity {
    #[Property, Primary]
    private int|null $id;

    #[Property]
    private string $title;

    #[Property, ManyHasOne(Author::class, "books")]
    private ManyHasOne $author;

    #[Property, ManyHasOne(Author::class, "translatedBooks")]
    private ManyHasOne $translator;

    #[Property, ManyHasMany(Tag::class, "books", isMain: true)]
    private ManyHasMany $tags;

    #[Property]
    private DateTimeImmutable $publishedAt = new DateTimeImmutable();

    #[Property, Embeddable(Money::class, isNullable: true)]
    private EmbeddableWrapper $price;
}
```

Pros:
- better memory consumption
- property modifier functionality will be covered mostly by IDE 

Cons:
- IDE plugin still needed for magic getters/setters.
- actual type will have be partially covered for property wrapper (relationship, etc.), with further possible migration to wrappers (e.g. DateTime support migrated to wrapper), this is problematic
- more verbose then PHPDOC
- BC break, at least switching to new syntax will require rewrite of getters/setters since magic cannot handle direct access to private property 

-------

**Duplicate in PhpDoc**; this is somehow not pleasant and too verbose; Orm strives for clarity and readablity. Without code example.

-------

Other solution? Please propose.

**Comment by JanTvrdik** [comment]
Looks to me like the current PHPDoc approach is better. By a lot.

**Comment by hrach** [comment]
Closing (at least for now). No viable proposal.

**Comment by maryo** [comment]
I've never used this library. Just looking for Doctrine alternative without DQL. Looks very nice from the first sight...
I was just asking myself "why isn't the phpdoc" at least on the properties itself? So I've searched the issues and found this one...

I believe there are good reasons behind the currect solutions just if I was ever goind to write something like this without needing to care of BC breaks...

```
/**
 * I am a value object with one property and I don't need any prefixes
 */
class Email {
    private $email;

    #[Virtual]
    private string $extraProperty;
    
    public function __construct(string $email)
    {
        $this->email = $email;
    }
}

/**
 * I am a value object with one property and I don't need any prefixes
 */
class DateRange {
    private \DateTimeImmutable $from;
    private \DateTimeImmutable $to;
    
    public function __construct(\DateTimeImmutable $from, \DateTimeImmutable $to)
    {
        $this->from = $from;
        $this->to = $to;
    }
}

class Book extends Entity
{
    #[Primary]
    private Uuid $id;
    
    /** I am a value object since I am no entity and I am also not a Collection an i have just a single column thus I don't want to be prefixed */
    private Email $email;

    private string $title;
    
    /**
     * I am an author, an entity and I don't want to be wrapped in any way :-/.
     * Doctrine also doesn't use any wrapper but PersistentCollection
     * Even Proxy classes which Doctrine uses are not needed in this case since lazy loading is done using magic __get and __set I guess
     * And event the property is set now it can be unset inside the abstract Entity
     */
    #[ManyHasOne("books")]
    private Author $author;

    #[ManyHasOne("translatedBooks")]
    private Translator $translator;

    /**
     * I will become an instance of something like an ArrayCollection in case I am constructed by the user or PersitentCollection in case of retrieving from the database
     */
    #[ManyHasMany(Tag::class, "books", isMain: true)]
    private Collection $tags;

    private DateTimeImmutable $publishedAt = new DateTimeImmutable;

    private DateRange $dateRange;

    #[Virtual]
    private string $extraProperty;
}
```

**Comment by hrach** [comment]
Thanks for the proposal. 

There are two main issues here:
- it would be more difficult to use the laziness -> accessing the property directly would throw since it would be a null, so the inner access would have to use getters the same as from outside -> avoid using the private property; it isn't only about these object type, but we also postpone validation of fetched data (strings, ints, ...)
- the typesafety would be still partial, since we miss generics, and access would be driven through getters/setters, where we should probably keep the type checks.

TBH BC breaks are probably the smalleest issue here since if this would be introduced, it would be an alternative implementation of Entity and you could migrate gradually. The point here is that having what we have - there is not a big gain to change if from the ground up.

**Comment by maryo** [comment]
Not sure I understand the problem correctly because everything I need to work works for me :-). https://3v4l.org/EKRfZ

```php
<?php

abstract class Entity
{
    public function __construct()
    {
        foreach ((new \ReflectionClass(static::class))->getProperties() as $reflectionProperty) {
            $reset = function (string $property) {
                $value = $this->$property ?? null;
                unset($this->$property);

                if ($value !== null) {
                    $this->$property = $value;
                }
            };
            $reset = $reset->bindTo($this, $reflectionProperty->getDeclaringClass()->name);
            $reset($reflectionProperty->name);
        }
    }
    
    // Let's pretend I don't care I've just made all private properties public for now and that private property collisions are possible when using inheritance

    public function __get(string $property)
    {
        echo "Lazily loading property {$property}.\n";

        // Let's pretend we are loading lazily but validation stuff can also happen here since __get is now called for each property 
        if (static::class === Book::class) {
            if ($property === 'author') {
                $this->setValue('author', new Author);
            } elseif ($property === 'collection') {
                $this->setValue('collection', new ArrayCollection);
            }
        }
        
        return $this->getValue($property);
    }
    
    public function __set(string $property, $value): void
    {
        $this->setValue($property, $value);
    }
    
    private function getValue(string $property)
    {
        $get = function (string $property) {
            return $this->$property;
        };
        $get = $get->bindTo($this, static::class);

        return $get($property);
    }

    private function setValue(string $property, $value): void
    {
        $set = function (string $property, $value) {
            $this->$property = $value;
        };
        $set = $set->bindTo($this, static::class);
        $set($property, $value);
    }
}

interface Collection
{}

class ArrayCollection implements Collection
{}

class Book extends Entity
{
    private Author $author;
    private Collection $collection;
    
    public function getAuthor(): Author
    {
        return $this->author;
    }

    public function getCollection(): Collection
    {
        return $this->collection;
    }
}

class Author
{}

$book = new Book;
print_r($book); // The object is completely empty, there is no author yet
assert($book->getAuthor() instanceof Author);
assert($book->getCollection() instanceof Collection);
print_r($book); // The object is now complete
```

**Comment by hrach** [comment]
Yes, we may do such reflection magic, but what's then the added value? We have to have all the magic the same way as before and the added value is minimal. (And the definition/list of properties is longer) What's more, now basic PhpStorm functionality doesn't see the properties form the outside - the plugin is then needed more than ever. Not speaking about other IDEs/editors, when we don't provide it.

**Comment by mabar** [comment]
I would go with public properties. With unset() of all initialized properties in constructor can be __set and __get utilized for lazy-loading, internal getters/setters, wrappers, ...

IDE plugin would have to provide only hints for generic collections and the `get|FindBy('author->name')` expressions.

I believe even protected properties could be supported, user would just have to define public getters/setters (not called by the orm).

```php
class Book extends AttributeEntity {
    #[Property, Primary]
    public int|null $id;

    #[Property]
    public string $title;

    #[Property, ManyHasOne(Author::class, "books")]
    public ManyHasOne $author;

    #[Property, ManyHasOne(Author::class, "translatedBooks")]
    public ManyHasOne $translator;

    #[Property, ManyHasMany(Tag::class, "books", isMain: true)]
    public ManyHasMany $tags;

    #[Property]
    public DateTimeImmutable $publishedAt = new DateTimeImmutable();

    #[Property, Wrapper(MoneyWrapper::class)]
    public ?Money $price;
}
```

**Comment by maryo** [comment]
> what's then the added value?
That you can still hook into the getter/setter from the Entity baseclass even it is declared with a default value etc to do the black magic.

> And the definition/list of properties is longer
Well... It's idiomatic PHP, not docblocks. That's a benefit for me. You define a type with a typehint, nullability etc like it was an ordinary property because it actually is just a property.

> doesn't see the properties form the outside
But I don't want them to be visible from outside. That's why they're private.
Is that actually possible with the current solution? I see that it is not such an issue in case of read-only property but I'd like to be able to hide some of them. I am not interested in features like Nette\SmartObject. I prefer plain PHP.

If I want them to be visible from outside I would make them public and lazyloading would still work. I wouldn't need any plugin in this case because I'd design the Collection as an interface that has all (or most) common methods of all Collection implementations.

@mabar was a little bit faster so yes that's exactly it. I just prefer private properties and limited getters. Event the private properties are possible. They would just behave like... private properties :-)

**Comment by mabar** [comment]
Protected and/or public properties, please. Private properties are the worst for that kind of code. In php it's possible by design to access child properties from parent. Except for private properties, which have to be accessed via reflection. Also all classes in inheritance chain can define property with same name. It breaks open-closed principles.

**Comment by mabar** [comment]
Let's add some pros for real public/protected properties with attributes:
- type-safe (I know, not for generics but it gives us what php has and collection can validate themself)
- domain design of entity is not affected by how orm works internally (throwing domain exceptions is huge deal for me)
- phpdoc can be dropped from opcache
- property types are defined by php and can be trusted
  - orm can check mismatches of types and metadata
  - wrapper can be moved from phpdoc/attribute to config - if orm finds type Money, it would know to use MoneyWrapper. For union types could be used multiple wrappers (one for each type from union). More than wrapper it's just an internal handler for property type.

**Comment by maryo** [comment]
What kind of code ? Protected is probably a little bit easier to implement because of the issues you mentioned but since reading the attributes also needs reflection and creating the object without calling it's constructor also needs reflection then I think the freedom is better.

`Also all classes in inheritance chain can define property with same name`

Yes. That's a limitation. I think that Doctrine throws an exception in such case. But I see the point. I can live with the protected ones :-)

Even though I prefer a data mapper that provides less opinionated way of structuring my classes as possible.

**Comment by JanTvrdik** [comment]
All I see is that you invented a way to have entity definition 7 times longer (at minimum).

**Comment by mabar** [comment]
7 times? 2 lines of code for property plus empty lines for formatting. 3 times at max. Yeah, nothing will be same length or shorter than phpdoc but phpdoc is still just a workaround, not a part of the language.

**Comment by JanTvrdik** [comment]
And another 4 lines for getter.

**Comment by mabar** [comment]
Which is purely optional feature, not a limitation. Public properties and no getters can be used.
