### ISSUE TITLE
assert class_exists should support also interface

### ISSUE THREAD

**Issue by japlavaren** [nextras/orm#471]
I have definition of valid values as interface
```
* @property string $connectionType {enum IElectricityConnectionType::CONNECTION_*}
```
problem is, that current version of nextras orm is checking `assert(class_exists($className))` but do not check `interface_exists` [source code](https://github.com/nextras/orm/blob/master/src/Entity/Reflection/ModifierParser.php#L230)

I think this line should be changed to 
```
assert(class_exists($className) || interface_exists($className));
```
to solve this problem

**Comment by hrach** [comment]
Let's say it is more likely a feature request. :)

Please be aware the it is highly recommended to switch some proper enum implementation like https://github.com/marc-mabe/php-enum which will preserve typesafety across all usage of the enum.
