### ISSUE TITLE
Is there a way to attach custom properties to the joining table without creating a via Entity?

### ISSUE THREAD

**Issue by davidkregl** [nextras/orm#479]
@hrach Hey! 

I am trying to figure out, how to store some additional parameters to the joining table of a relationship between two entities. Let's say I have an Entity `Order` and `Product`. Currently, I am trying to add Products to the Order but need to specify some additional parameters such as quantity of the product, etc.

What is the best practice for achieving this behaviour? The first thing that came to my mind was to create an Entity OrderProducts and define it's structure there with reference to the order and to the product and the additional data.

Is this the recommended way of doing this or is there a better one? 

Thank you in advance,

David

**Comment by hrach** [comment]
> Is this the recommended way of doing this or is there a better one?

Yes, it is.

*I would name the entity OrderItem*

**Comment by davidkregl** [comment]
> > Is this the recommended way of doing this?
> 
> Yes, it is.
> 
> _I would name the entity OrderItem_

Wow! That was a rocket speed reply. Thank you! 🚀

**Comment by davidkregl** [comment]
@hrach Would you recommend defining the Item Entity under Order namespace?

![Screen Shot 2021-01-11 at 16 40 23](https://user-images.githubusercontent.com/5594883/104202836-b4e27900-542b-11eb-971e-e1396971f1b6.png)

**Comment by hrach** [comment]
I would rather create feature modules and create namespace for each entity on the same level in the feature module. Not sure how big your app is, but Item as a class name is not ideal so I would go rather with full name (OfferItem, OrderItem, ...)

**Comment by hrach** [comment]
Closing here. Eventually feel free to open new issues/question or use discussions here on GitHub.

**Comment by davidkregl** [comment]
@hrach The project I am working on is quite large and I am still in the begginning. What you are suggesting is to create let's say a OfferModule and hide all related functionality MVC layers under this module and access it from outside? I quite favor this approach. Thank you!
