### ISSUE TITLE
Table reflection exception - windows only

### ISSUE THREAD

**Issue by mskocik** [nextras/orm#481]
**Describe the bug**
This bug is windows-only.   
When you have defined entity table name which is not completely lowercase you got this exception from `Conventions.php:137`
![image](https://user-images.githubusercontent.com/25513620/105880801-0f6efe00-6004-11eb-8227-bef102201036.png)

Where `$table->name` = `user` and `$tableName` = `User`

**To Reproduce**
Imagine setup - **windows server**

_Entity Mapper_
```php
class UserMapper extends BaseMapper
{
    protected $tableName = 'User';
...
```

_MySQL DB table User_   

![image](https://user-images.githubusercontent.com/25513620/105880456-abe4d080-6003-11eb-98b4-2b5293f93af7.png)```

**Expected behavior**
Should work fine. This starts to break with version 4.0 where StorageReflection has been reworked to Conventions.

**Versions::**
 - OS: windows
 - Orm: [e.g. Orm 4.0]
 - Database: [e.g. MySQL 5.7]

**Comment by hrach** [comment]
It seems that this is a feature and Mysql's attribute. You may try to change your Mysql setting `lower_case_table_names` to `2` to avoid this issue: https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html

Feel free to ask to reopen. Yet I'm not sure what should be done on Orm's side.

**Comment by mskocik** [comment]
This won't help, because this is db-related setting, but the error is triggered on PHP side on this line:
https://github.com/nextras/orm/blob/11ed0b7f202b48e16f05e3d2cc93fa5f96a38a86/src/Mapper/Dbal/Conventions/Conventions.php#L131

The only solution I came with is to extend the condition when default check fails and on windows, compare lowercase table names.

```php
if ($table->name === $tableName || (PHP_OS_FAMILY === 'Windows' && strtolower($table->name) === strtolower($tableName))) {
```

What do you think?

**Comment by hrach** [comment]
The error is correct since the table name is returned from mysql as lowercased. The proposed switch is not ideal. Why the db setting does not work? I can imagine making the method protected to allow you override it.

**Comment by mskocik** [comment]
Db setting doesn't work because of this: 

> MySQL converts them to lowercase on lookup

It can be clearly seen in adminer interface: in sidebar correctly named table, in main view lowercase.
![image](https://user-images.githubusercontent.com/25513620/106387846-ec659500-63db-11eb-9e84-17f229260137.png)

The proposed switch may not be ideal, but from my point of view it's better than changing method visibility, because _it just works_. Of course I would appriecate also visibility change. Now I have it rewritten in local vendor dir, which is far from ideal :)

**Comment by hrach** [comment]
> Use lower_case_table_names=0 on Unix and lower_case_table_names=2 on Windows. This preserves the lettercase of database and table names. The disadvantage of this is that you must ensure that your statements always refer to your database and table names with the correct lettercase on Windows. If you transfer your statements to Unix, where lettercase is significant, they do not work if the lettercase is incorrect. 

I still don't have an answer why this does not work. I have tried to modify my setup (actually it has to be setupped from beginning, so I have reinstalled my local mysql for you) and it works nicely, the query correctly returns upper-cased table name.

![image](https://user-images.githubusercontent.com/284263/106391315-f774f100-63ec-11eb-957b-9f87624d3c0c.png)
![image](https://user-images.githubusercontent.com/284263/106391337-14112900-63ed-11eb-8c06-0dabefffa70e.png)

So my first answer definitely holds. You have wrongly setup-ed db on Windows. I understand that it may be difficult/impossible to reconfigure so I offer making it protected.

**Comment by mskocik** [comment]
> actually it has to be setupped from beginning,

With this I was also able to replicate working setup. When I am thinking about it, it doesn't really make sense to update code in any way. I will re-import my db, it's no big deal since I've already installed new db version.

Thanks for pointing the need of correct setting before creating database. Consider this closed 👍

**Comment by hrach** [comment]
Thanks for the confirmation. :)
