### ISSUE TITLE
Ordering by Embeddable property

### ISSUE THREAD

**Issue by stpnkcrk** [nextras/orm#500]
**Describe the bug**
Ordering by Embeddable property doesn't work.

**To Reproduce**
`->orderBy('name->last')` skonci chybou `Unknown column 'clients.name->last' in 'order clause'`
`->orderBy('name_last')` skonci chybou `Undefined property ChovIS\BackOffice\Model\Clients\Client\Client::$name_last.`

**Expected behavior**
Ordering by Embeddable property works.

**Versions::**
 - Database: MariaDB 10.3.28
 - Orm: 4.0.1
 - Dbal: 4.0.2

**Comment by hrach** [comment]
Hi, thank you for the report. I have added tests covering this and it seems to work. [1c9a840632301d32444d777975bddbed27a774be] Could you describe with a more detailed example when it fails? Thank you.

**Comment by stpnkcrk** [comment]
🤦 I have no idea why or how, but it's working now.
