### ISSUE TITLE
How to create where - group by queries without querybuilder?

### ISSUE THREAD

**Issue by milsorm** [nextras/orm#501]
If I use CountAggregateFunction inside findBy(), every condition from findBy went to HAVING clause. But I want to use all of these in WHERE clause, than perform aggregation and (possibly) something makes in HAVING or leave HAVING empty.

How can I distinguish, which conditions go to WHERE and which to HAVING?

**Comment by hrach** [comment]
If I understand your query correctly, you are doing multiple filtering in findBy() and one of them is an aggregation and others not. Yes, it is currently buggy. 

Could you please [try out this PR which could fix it](https://github.com/nextras/orm/pull/496)? It does extensive rewrite of the query so I need to more verification it doesn't break anything else.

**Comment by milsorm** [comment]
No no, I am probably doing something which is outside of ORM scope.

I have a table with many records and repository-mapper-entity for individual access to these records. But I also need classic

`SELECT something,COUNT(*) FROM table GROUP BY something
`

but even if I use queryBuilder for building that query with usage of entity definition, I have no access to COUNT(*) column because it cannot be described in entity. Probably it is necessary to build view for every group-by select and build individual repository-mapper-entity set for every view or use only DBAL layer (no ORM)... Am I right? Or is there any theoretical construct how to create sub-summary over entities without iterating over all records?

**Comment by hrach** [comment]
You may override the DbalMapper's builder method to select these data for your entity. But ORM is definitely designed for this type of selects. You can also utilize an actual column and update its content with triggers.

**Comment by hrach** [comment]
Closing as I don't see potential to support selecting a grouped result explicitly.
You may have try overriding DbalMapper::builder() method to return such query and avoid storing that column.

**Comment by milsorm** [comment]
My solution:
- descend DbalCollection - findByGroupBy which is able to call processFilterFunction through helper for where, group by and having clauses
- descend Mapper to creaet my new descendant collection instead of DbalCollection (in findAll()) and allow to call this method from collection 
- descend Repository to allow call this method from mapper
- create second entity with read properties for aggregation columns
- add detection to Repository to choose original entity class and aggregation entity class if aggregation fields are returned (which entity to populate)

The only pity is that I need to identify such aggregation column to same name as property in aggregation entity. So I used "aggregatedValue" and it is constant name in my DbalCollection descendant and in aggregation entities.

Much better solution can be some virtual property in entity for storing aggregation values and detect its name in my DbalCollection descendant.

The result is that all rows in aggregated queries are still entities and works perfectly in grids, tables etc.

**Comment by hrach** [comment]
Oh, sorry, the sentence misses the most important work - NOT. :D

**Comment by milsorm** [comment]
That makes sense :-)

OK, nevermind, solution found, it is only 10 minutes more work in every aggregation.

Thanks for great ORM anyway.
