### ISSUE TITLE
Filter by relation 1:1

### ISSUE THREAD

**Issue by romanmatyus** [nextras/orm#525]
I have table ```BankTransaction``` with operations on bank account.

Next table is ```Order```. Order is specific, is always payed only with max one transaction.

Transaction can be paired with Order, but not necessarily.

```php
/**
 * @property BankTransaction|null  $bankTransaction {1:1 BankTransaction::$order, isMain=true}
 */
class Order extends Entity {}
```

```php
/**
 * @property Order|null              $order {1:1 Order::$bankTransaction}
 */
class BankTransaction extends Entity {}
```

Is possible filter all ```BankTransation``` where is not paired to ```Order```?

Something like this (inspired by Nette Database Explorer):

```php
foreach ($this->orm->bankTransactions->findBy([
	':order->bankTransaction' => null, // or 'order' => null
]) as $bankTransaction) {}
```

Thanks!

**Comment by mabar** [comment]
You don't have to care whether the relationship is stored on `Order` side, just filter by the property. Where is the relationship stored orm knows from `isMain=true`
```
$this->orm->bankTransactions->findBy([
	'order' => null,
])
```

**Comment by hrach** [comment]
Mabar's answer should be the answer. Thanks!
