### ISSUE TITLE
Remove ORDER BY when counting collection items

### ISSUE THREAD

**Issue by mrceperka** [nextras/orm#529]
**Describe the bug**
Calling `$collection->countStored()` should remove `ORDER BY` clause

**To Reproduce**
```php
// SomeMapper.php

$builder->addOrderBy('id');
$builder->limitBy(10, 0);
// ...
$collection = $this->toCollection($builder);

// counting with ORDER BY, which is weird, because order does not matter
$total = $collection->countStored();


// hotfix
$collection  = $this->toCollection((clone $builder)->orderBy(null));
// counting without ORDER BY
$total = $collection->countStored();
```

**Expected behavior**
`ORDER BY` clause should be removed

**Versions:**
 - Database: mariadb 10.4
 - Orm: 4.0
 - Dbal: 4.0
 
**TODO**
 - test case
 - PR with fix

**Comment by mrceperka** [comment]
@hrach can this `if` statement be removed?
https://github.com/nextras/orm/blob/82d0cfc277828ad71cbe66c02fb9de0577a7d74c/src/Collection/DbalCollection.php#L311

**Comment by hrach** [comment]
Probably. Not fully sure now what was the reason for it. You may try it and see if any test "needs it".

**Comment by mrceperka** [comment]
> Probably. Not fully sure now what was the reason for it. You may try it and see if any test "needs it".

I've found it :(
```
-- FAILED: integration/Collection/collection.phpt dataprovider=sqlsrv|/home/runner/work/orm/orm/tests/cases/integration/Collection/../../../databases.ini method=testCountStoredDbalWithoutOrderByClause
   Exited with error code 255 (expected 0)
   Nextras\Dbal\Drivers\Exception\QueryException: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'OFFSET'.
   ```

**Comment by hrach** [comment]
We could workaround it and keep the ordering only for MSSQL.
