### ISSUE TITLE
Support multiple repositories for STI

### ISSUE THREAD

**Issue by TonnyJe** [nextras/orm#601]
I want to ask if there is any way to solve the problem with one repository for multiple entities created by STI?

For example, let's have a `User` table where we will have customers and merchants together, whose status will be distinguished by a column with an ENUM value. Since merchant and customer can have multiple roles, it is more about the type of user than the role of the user.

So we will use STI and have a `Merchant` class and a `Customer` class in the application.

Then when I have a repository, it looks something like this, which causes a huge duplication of code:

```php
<?php declare(strict_types=1);

namespace App\Model\Db\Repository;

use Nextras\Orm\Repository\Repository;
use App\Model\Db\Entity\Client;
use App\Model\Db\Entity\Merchant;
use App\Model\Db\Entity\User;

class UserRepository extends Repository
{
    public static function getEntityClassNames(): array
    {
        return [
            User::class,
            Client::class,
            Merchant::class,
        ];
    }

    public function getEntityClassName(array $data): string
    {
        return match ($data['type']) {
            User::TYPE_MERCHANT => Merchant::class,
            User::TYPE_CLIENT => Client::class,
            default => parent::getEntityClassName($data),
        };
    }
    
    public function getClientByEmail(string $email): Client
    {
        return $this->getBy([
            'email' => $email,
            'type' => User::TYPE_CLIENT,
        ]);
    }
    
    public function getMerchantByEmail(string $email): Merchant
    {
        return $this->getBy([
            'email' => $email,
            'type' => User::TYPE_MERCHANT,
        ]);
    }
}
```
Or (which is worse, since the caller has to explicitly specify for each call whether it wants a customer or a merchant):
```php
<?php declare(strict_types=1);

namespace App\Model\Db\Repository;

use Nextras\Orm\Repository\Repository;
use App\Model\Db\Entity\Client;
use App\Model\Db\Entity\Merchant;
use App\Model\Db\Entity\User;

class UserRepository extends Repository
{
    public static function getEntityClassNames(): array
    {
        return [
            User::class,
            Client::class,
            Merchant::class,
        ];
    }

    public function getEntityClassName(array $data): string
    {
        return match ($data['type']) {
            User::TYPE_MERCHANT => Merchant::class,
            User::TYPE_CLIENT => Client::class,
            default => parent::getEntityClassName($data),
        };
    }
    
    public function getByEmail(string $email, int $type): Client
    {
        return $this->getBy([
            'email' => $email,
            'type' => $type,
        ]);
    }
}
```

But I don't want to pass some generic User repository to the classes where I'm only going to work with Merchants, and then have to call different methods on top of the generic repository for the same action, but I would like to call a method where I don't have to distinguish whether I want Merchants or Customers.

Respectively, instead of the class described above, I'd like to have something like this:
```php
abstract class UserRepository extends Repository
{
    protected abstract function getActualType();

    public static function getEntityClassNames(): array
    {
        return [
            User::class,
            Client::class,
            Merchant::class,
        ];
    }

    public function getEntityClassName(array $data): string
    {
        return match ($data['type']) {
            User::TYPE_MERCHANT => Merchant::class,
            User::TYPE_CLIENT => Client::class,
            default => parent::getEntityClassName($data),
        };
    }

    public function getBy(array $conds): ?IEntity
    {
        $data['type'] = $this->getActualType();
        return parent::getBy($data);
    }

    public function getByEmail(string $email): User
    {
        return $this->getBy([
            'email' => $email,
        ]);
    }
}

class MerchantRepository extends UserRepository
{
    protected function getActualType(): int
    {
        return User::TYPE_MERCHANT;
    }
}

class ClientRepository extends UserRepository
{
    protected function getActualType(): int
    {
        return User::TYPE_CLIENT;
    }
    // In case you need to force return type to global methods :D
    public function getByEmail(string $email): Client
    {
        return parent::getByEmail($email);
    }
}
```

Is this somehow achievable now?

So far I've achieved this by creating a complete intermediate layer, using composition instead of inheritance, and creating repositories outside the ORM and then calling the ORM from them, but that doesn't seem like the right way to go.

Another option to use ORM directly I thought of was to just make 2 tables in the database, but again this will be duplication, since I'll have to store the same data that I just want to work with differently in two tables, which means that suddenly the files for cars will be something different from the files for bread, which I don't like.

**Comment by hrach** [comment]
It seems that your use awe is not a STI. Simply split two repos to be completely separated yet working with the same db table. Then override mapper's builder function to add this type automatically.

**Comment by hrach** [comment]
STI is for multiple entity types in single repository.

**Comment by TonnyJe** [comment]
Tento problém ale nastává při každém použití STI.
Prostě pokud mám nějakou entitu, tak bych měl k ní ideálně mít její konkrétní repozitář. 

Pokud se nepletu, tak STI je definováno jako 'Když různé entity mají stejná data a tedy sdílejí stejnou databázovou tabulku, ale mají jiné chování a tedy se s každou entitou jinak pracuje'.
A pak je tu ještě MTI, které je definováno jako 'Když má spousta entit různá data, takže má každá svou databázovou tabulku, ale chceme s nimi pracovat stejně a tedy potřebujeme stejnou funkčnost pro různá data'

Jako příklad STI tedy může být právě zákazník/obchodník, kdy chci o uživatelích obecně ukládat stejná data, ale se zákazníkem pracovat jinak, než s obchodníkem a jako příklad MTI může být, když máme třeba notifikace, kdy některé jsou PushNotifikace, některé E-mailové, některé systémové a jiné zase přes SMS apod. U každé uchováváme společná data, jako je zpráva a čas odeslání, ale každá má zase svá data, kde jedna chce E-mail, druhá telefonní číslo, třetí identifikátor osoby atp. Dát to do jedné tabulky by bylo zbytečné pro mnoho nullable sloupců a tak se to rozdělí na více tabulek, ale všechny mají stejné chování, jako je odeslat, a vybírat a odesílat chceme vždy všechny notifikace naráz nehledě na to, jestli to jsou PUSH, mail, sms atp.


Pokud se tedy nepletu, tak to znamená, že u STI by každá entita měla mít vlastní Repozitář, kde bude člověk pracovat pouze s daty od konkrétní entity, jelikož tyto entity sdílejí data, ale ne logiku, tedy logika je jiná a použitím jednoho repozitáře porušujeme SingleResponsibility.

Naopak u MTI by měla být většina kódu společného v obecném repozitáři stejně, jak to nyní je u NestrasORM v rámci STI, jelikož aplikace nebude v 90% případů potřebovat vědět, s jakou konkrétní instancí pracuje.

Tedy si myslím, že mé použití STI je na místě a proto mi tato možnost chybí a posílal jsem tento dotaz.

**Comment by hrach** [comment]
> If I'm not mistaken, STI is defined as 'When different entities have the same data and thus share the same database table, but have different behaviors and thus each entity is handled differently'.

Nextras Orm models this with a single repository - if you want the STI. Also, Nextras also supports "not exposing" all data with a different type. 

What I recommend is to start another way around - define the API you want to have (it seems to have two separate repositories), specify the storage you want to have - a single table and then make it work in the tool you want to use - in Nextras Orm this will best work when done how I described.

Nextras Orm can support STI. Your last example should somehow work. Though I'm not sure what has to be exactly overridden, because the "root" builder is a mapper and not find* methods on repository (especially for relationships, but maybe if you don't need this, it's quite ok to rewrite findBy and findAll)

**Comment by TonnyJe** [comment]
Thank you. I'll try your approach.
