### ISSUE TITLE
rep finder and own model

### ISSUE THREAD

**Issue by ZbyRih** [nextras/orm#602]
Its possible to combine Nextras\Orm\Bridges\NetteDI\DIRepositoryFinder
 and user defined model?

**Comment by hrach** [comment]
Could you please share more about your use case? thx

**Comment by hrach** [comment]
I'm sorry for the late reply.

This should be possible by introducing your own repository finder & repository loaders.
You may delegate to the original ones.

1. First, inherit both finders and override "setupRepositoryLoader" to add those finders with different names and as not autowired.
2. Create your finder that takes both built-in finders and executes them.
3. In your finder, add your custom loader that requires both not autowired finders.
4. Delegate from finder methods to respective finders. (E.g. when not found in phpdoc, use dic-based finder).
