### ISSUE TITLE
Can't update to dev-main from 4.0.6

### ISSUE THREAD

**Issue by pdrhlik** [nextras/orm#617]
**Describe the bug**
Running `composer require nextras/orm:dev-main --with-all-dependencies` doesn't work for me.

**To Reproduce**
Steps to reproduce the behavior. It could include:
My `composer.json` relevant packages are:

```json
"require": {
	"php" : ">=8.0",
	"nextras/orm": "4.0.6",
	"nette/application": "^3.1",
	"nette/robot-loader": "^3.4",
	"nette/bootstrap": "^3.1",
	"nette/caching": "^3.1",
	"nette/database": "^3.1",
	"nette/di": "^3.0",
	"nette/finder": "^2.5",
	"nette/forms": "^3.1",
	"nette/http": "^3.1",
	"nette/mail": "^3.1",
	"nette/security": "^3.1",
	"nette/utils": "^3.2",
	"latte/latte": "2.11",
	"tracy/tracy": "^2.8",
	"nette/routing": "^3.0",
	"nextras/dbal": "4.0.5"
}
```

The main issue seems to be with version of `nextras/dbal` and `nette/utils`.

**Expected behavior**
Upgrade should be smoother.

**Versions::**
 - PHP: 8.1
 - Database: MariaDB 10.7.3
 - Orm: 4.0.6
 - Dbal: 4.0.5

I didn't have too much time to spend on this so I'm just reporting the issue in case it could help with releasing the new version.

Cheers,
Patrik

**Comment by mabar** [comment]
`--with-all-dependencies` does not change version constraints. You have to update also nextras/dbal to dev version.

For nette/utils, simplest temporary workaround is `"nette/utils": "4.0.0 as 3.2.9"`

**Comment by hrach** [comment]
main branch now supports nette utils 3.x as well. thanks for reporting this
