### ISSUE TITLE
Entity dumping in 5.6

### ISSUE THREAD

**Issue by hrach** [nextras/orm#64]
```
Fatal Error
__debuginfo() must return an array
```
need investigation. DataEntityFragment::$data is an array.

**Comment by hrach** [comment]
cc @MartinMajor could you please provide failing example? It works for me :-)

**Comment by JanTvrdik** [comment]
I can just confirm that I've seen this error too. Maybe it's a PHP bug.

**Comment by MartinMajor** [comment]
This is config for [PuPHPet](https://puphpet.com/). Just drag-n-drop config file to webpage and generate vagrant config:
https://gist.github.com/MartinMajor/ebad7815156f4107e512

And then almost any var_dump fails. Eg:

```php
var_dump($orm->books->getById(1));
```

It is probably some PHP bug, because it also kills php-fpm.
