### ISSUE TITLE
Simple ORM extension for php-di/php-di

### ISSUE THREAD

**Issue by Zarganwar** [nextras/orm#647]
Hi,

This is just an informational note.

I have created a very simple [extension](https://github.com/Zarganwar/php-di-nextras-orm-extension) for [PHP-DI](https://php-di.org/). PHP-DI is commonly used in the Slim framework and is also compatible with Symfony.

Best regards!

**Comment by hrach** [comment]
Thanks for sharing. I'm putting a link into readme.
