### ISSUE TITLE
incorrect time zone: 'Europe/Prague'

### ISSUE THREAD

**Issue by czTomasphp** [nextras/orm#656]
po nainstalovani orm-demo-nette
vyhozena hlaska 
In MysqliDriver.php line 449:
Unknown or incorrect time zone: 'Europe/Prague'

**Comment by stpnkcrk** [comment]
https://nextras.org/dbal/docs/main/timezones-mysql-support

**Comment by hrach** [comment]
Because this is quite common, the next version of Dbal (5.0) prints additional info:
https://github.com/nextras/dbal/pull/232/commits/647db40033de25f281f856081352db40041f0a6b
