### ISSUE TITLE
Unknown column in HAVING clause

### ISSUE THREAD

**Issue by stepapo** [nextras/orm#662]
**Describe the bug**

I tried RC version of 5.0 and so far so good except for one thing in MySQL. It's connected to [this comment](https://github.com/nextras/orm/issues/526#issuecomment-1065956019). That bug was fixed, difference is in `IColletion::OR` operator. The reason remains the same, two columns with the same name from different tables in HAVING clause. This works in 4.0

**To Reproduce**
```
$books = $this->orm->books->findBy([
  ICollection::OR,
  'tags->id' => 1,
  'author->name' => 'Writer 1',
  'publisher->name' => 'Nextras publisher A',
]);
Assert::same($books->count(), 3);
```
`MySQL: Unknown column 'author.name' in 'having clause'`

**Versions**
 - Database: MariaDB 11.0.2
 - Orm: 5.0.0-rc1
 - Dbal: 5.0.0-rc4

**Comment by hrach** [comment]
Thank you for testing and this report. It seems now there is a lot of "infrastructure" to be able to fix this :)
