### ISSUE TITLE
Persisting entity populates generated values in storage engine

### ISSUE THREAD

**Issue by hrach** [nextras/orm#68]
Like `INSERT INTO "table" ("text") VALUES ("baf") RETURNING *;`

**Comment by hrach** [comment]
The question is how should the interface look like.

**Comment by Mikulas** [comment]
- `string[] getListOfSelfUpdatingFields()`: if not empty, queries will be generated with returning clause
- `void updateFields(Entity, array $rawData)`: maps returned fields `$rawData` to entity
    - default implementation would be `1:1` map of translated field columns to property names

This would not be generic enough though. For example, when using postgis, one might have `lat`, `lng` properties on entity, but one `ST_Point` field in database. To properly map this back to two properties, the returning clause would have to be user defined (`returning ST_AsText(location)` in this case).

So `getListOfSelfUpdatingFields` could be of `%ex` syntax? Most users would have something like `return ['%column', 'foo'];` which is not that great though.

**Comment by Mikulas** [comment]
Should this feature also support updates of related entities?

Something like
```
table article(computedCommentCount);
table comments(articleId);

trigger: after insert into comments, increment article.computedCommentCount
```

```sql
insert into comments (...) returning (article.computedCommentCount + 1 as newCount)
```

This example is too simple and could be solved in php as well, but it illustrates the problem.
