### ISSUE TITLE
Forcing separate AnyAggregator and NoneAgregator for specific conditions

### ISSUE THREAD

**Issue by stepapo** [nextras/orm#688]
Not really a bug, just an observation for reference, and potential feature request.

1. This would seemingly find books with both tags 1 and 2.
```php
$this->model->books->findBy([
	ICollection::AND,
	['tags->id' => 1],
	['tags->id' => 2],
]);
```
However it does not as it uses same JOIN alias for both conditions, resulting in conditions filtering each other out. A workaround has to be used, which creates separate aliases:
```php
$this->model->books->findBy([
	ICollection::AND,
	[ICollection::AND, new AnyAggregator('1'), 'tags->id' => 1],
	[ICollection::AND, new AnyAggregator('2'), 'tags->id' => 2],
])
```
Question is, couldn't separate JOIN aliases be created automatically for HasMany properties (possibly only in AND context)?

2. Similarly, this does not find books without tag 1:
```php
$this->model->books->findBy(['tags->id!=' => 1]);
```
For this to work, usage of NoneAggregator has to be explicit:
```php
$this->model->books->findBy([ICollection::AND, new NoneAggregator, 'tags->id' => 1]);
```
Could usage of NoneAggregator be forced in this context? The same way I believe AnyAggregator is forced for condition `['tags->id' => 1]`.

**Comment by hrach** [comment]
**1**

> This would seemingly find books with both tags 1 and 2.

Well, not necessarily.

```php
$this->model->books->findBy([
	ICollection::AND,
	['tags->title~' => LikeExpression::endsWith('New')],
	['tags->title~' => LikeExpression::startsWith('Top')],
]);
```

In this example (not targeting PK) it is kinda not obvious that the proposed behavior is (always) wanted.

We (try to) targeted PHP-like syntax, i.e. the mental model was rather

```php
foreach ($tags as $tag) {
   if ($tag->id === 1 && $tag->id === 2) return true;
}
return false;
```

than 

```php
foreach ($tags as $tag) {
   if ($tag->id === 1) return true;
   if ($tag->id === 2) return true;
}
return false;
```

Note the fact that the second example somehow "misses" the AND (&&).

-----


**2**

Let's use the PHP-like mental model once again.

this: `$this->model->books->findBy(['tags->id!=' => 1]);`

gets translated to 

```php
foreach ($tags as $tag) {
   if ($tag->id != 1) return true;
}
return false;
```

With the implicit "any" and a little bit example it stars making sense once again:


```php
// is there a book that has any tag with non-default priority?
$this->model->books->findBy(['tags->priority!=' => 0]);
```

Keeping the behavior to hold implicit aggregation as Any makes quite sense to me.

**Comment by stepapo** [comment]
> ```
> foreach ($tags as $tag) {
>    if ($tag->id === 1) return true;
>    if ($tag->id === 2) return true;
> }
> return false;
> ```
Actually this is not what I am proposing. That would be OR. It's more like this:
```
foreach ($tags as $tag1) {
  foreach ($tags as $tag2) {
     if ($tag1->id === 1 && $tag2->id === 2) return true;
  }
}
return false;
```
So it does not miss the AND.

But I understand your reasoning. Basically, it's a matter of starting to use this in real life use cases. To see which behavior is desired more often. But you're right, for default behavior, it's probably best to leave it like it is.

**Comment by hrach** [comment]
> That would be OR.

Oh sorry, you're right 🤦.

Maybe if we realize, it is not the expected behavior, we could require being explicit.

**Comment by hrach** [comment]
Closing, at least for now.
