### ISSUE TITLE
Persisting entity with duplicit PK.

### ISSUE THREAD

**Issue by Keeehi** [nextras/orm#74]
hrach's translation edit: automatically call rollback when exception happen, or at leats allow persist the entity again.

------------

Mějme tento kód:
```php
$myEntity = new MyEntity();
$myEntity->id = 1;

try {
    $this->model->departments->persistAndFlush($myEntity);
} catch (Nette\Database\UniqueConstraintViolationException $e) {
    $myEntity->id = 2;
    $this->model->departments->persistAndFlush($myEntity);
}
```
Když entita s idčkem 1 v databázi neexistuje, pak je vše v pořádku. Pokud však existuje, vyvolá se výjimka a nastává problém. I když se nebudu pokoušet tu entitu podruhé uložit, očekával bych rollback. Sice nenásleduje commit, ale rollback by tam mohl být. Ovšem mnohem horší je, když se tu entitu pokusím upravit a znovu uložit. Hodnoty má nastavené teď tak, aby se to do databáze povedlo uložit. Ovšem nový insert se při druhém volání persistAndFlush se nevygeneruje, zato commit ano. Výsledkem je toto:
```
0.209	SET NAMES 'utf8mb4'
0.148	::beginTransaction
ERROR	INSERT INTO `my_entity` (`id`) VALUES (1)
0.191	::commit
```
Očekával bych rollback předchozí transakce a pokus o novou. Nebo alespoň vyhození výjimky že nejde znovu ukládat entitu jejíž uložení někdy předtím selhalo.

**Comment by hrach** [comment]
Well. From my point of view calling automatically wouldn't be ok. There can be more things in current transaction. But repeated persist call should function, so this is a bug.
