### ISSUE TITLE
Getting null field with default modifier will return default value

### ISSUE THREAD

**Issue by jtojnar** [nextras/orm#78]
Is this expected behaviour? I suppose not as it isn’t IMHO consistent with [EntityDefaultValueTest::testSetNULLValue()](https://github.com/nextras/orm/blob/master/tests/cases/integration/Entity/entity.defaultValue.phpt#L41)

Demonstration: https://github.com/jtojnar/orm-demo/compare/master...jtojnar:reading-null-default-now

It has been around for a while, even with nette/database.

Use case: legacy items don’t have known creation date so they should return null (which they have stored in db).

**Comment by hrach** [comment]
So, your proposal is to populate default value only if value is "undefined". (=unread & unpersisted).

**Comment by hrach** [comment]
Probably just extend the condition here: https://github.com/nextras/orm/blob/b27edab290631ee079111714645dae0df190d3f8/src/Entity/Fragments/DataEntityFragment.php#L396
to `if (!array_key_exists($name, $this->data) && !$entity->isPersisted()) {``

**Comment by jtojnar** [comment]
This causes `Undefined index` on [line 407](https://github.com/nextras/orm/blob/b27edab290631ee079111714645dae0df190d3f8/src/Entity/Fragments/DataEntityFragment.php#L407).

**Comment by jtojnar** [comment]
And adding isset reveals broken virtual properties.

**Comment by hrach** [comment]
Yes, of couse, it should look like 
```
if (!array_key_exists($name, $this->data)) {
     $this->data[$name] = !$entity->isPersisted() ? $propertyMetadata->defaultValue : NULL;
}
```
I don't get the comment about broken virtual properties.

**Comment by jtojnar** [comment]
I added isset on line 406 to suppress aforementioned undefined index but that revealed that the first change also broke virtual properties.

This seems to work, however (replacing $entity for $this). Thanks.

**Comment by jtojnar** [comment]
Tests don’t like it very much though:

> Nextras\Orm\InvalidStateException: Property NextrasTests\Orm\Author::$web is not set.

Not sure whether the tests should be changed or the behaviour implemented in another way.

**Comment by hrach** [comment]
It was "a little bit" more difficult. Needed changes in array mapper: https://github.com/nextras/orm/commit/548020be9c1080dfe3be29bd42aa47a165ac3900 https://github.com/nextras/orm/commit/f956fa3f3093a9f1e05154032eae05f2e547c34f
