### ISSUE TITLE
Blob support

### ISSUE THREAD

**Issue by PeterBocan** [nextras/orm#84]
Is there any kind of support for blobs?

**Comment by hrach** [comment]
Probably not, but I have never used it, it will be also highly connected to nextras/dbal.

**Comment by hrach** [comment]
Implemented support for both ORM and DBAL. The basic possible impl.:

```php
/**
 * @param string $contents
 */
class File extends Nextras\Orm\Entity\Entity
{
}

class FilesMapper extends DbalMapper
{
    protected function createStorageReflection()
    {
        $reflection = parent::createStorageReflection();
        $reflection->addMapping('contents', 'contents', NULL, function($val, & $key) {
             $key .= '%blob';
             return $val;
        });
        return $reflection;
    }
}
```

**Comment by insekticid** [comment]
after update to orm 1.1 clear memcache, otherwise you will get an error - Fatal error: Call to undefined function d() in nextras\orm\src\Mapper\Dbal\StorageReflection\StorageReflection.php
