### ISSUE TITLE
Entity - int + NULL error

### ISSUE THREAD

**Issue by f3l1x** [nextras/orm#86]
```php
/**
 * @property int|NULL   $fbid
 * @property string     $username
 * @property string     $password
 * @property string     $role           {default self::ROLE_USER} {enum self::ROLE_*}
 * @property DateTime   $loggedAt       {default now}
 * @property DateTime   $createdAt      {default now}
 */
```

Table has UNIQUE INDEX on $fbid and also it could be NULL. 

When I create/update user like this:

```php
// ...
$user->fbid = $fbid; # '12345678910'
$this->repository->flushAndPersist($user);
``` 
It throws `Nextras\Dbal\UniqueConstraintViolationException`

Duplicate entry '_ID OF FIRST USER_' for key 'fbid'.

How is that possible? Thx for advice.

**Comment by JanTvrdik** [comment]
How does the final SQL look like? Does it work if you execute the SQL manually (e.g. in Adminer)?

**Comment by hrach** [comment]
ping @f3l1x

**Comment by hrach** [comment]
ping @f3l1x

**Comment by f3l1x** [comment]
@JanTvrdik @hrach I have test it. Problem wasn't at ORM. I tried to store bigger integer that was a type for.

**Comment by hrach** [comment]
Thanks for clarification :)
