### ISSUE TITLE
Entity serialization support & tests

### ISSUE THREAD

**Issue by hrach** [nextras/orm#92]

**Comment by pavelmlejnek** [comment]
Hi, what is the current situation about entity (un)serialization? I noticed that the support was removed from 3.0. Is there anything planned in the future? Can I help somehow?

**Comment by hrach** [comment]
Currently, I have no intention to implement this. It's hard to do it correctly: if we want to reload entity from serialized version, we have to somehow attach it to the repository again. That's almost impossible to do this automatically (without some static magic). Also, I do not consider it clever to store entities. Better ways is store (serialize) their ids and fetch them again. What is your usecase?

**Comment by pavelmlejnek** [comment]
I just wanted to cache dynamic ACL entities (Permission, Role, Resource) and avoid unnecessary DB queries.

**Comment by hrach** [comment]
Not planned.
